### ISSUE TITLE
HttpException class conflict with PECL extension

### ISSUE THREAD

**Issue by ludofleury** [bobthecow/genghis#10]
Since genghis isn't namespaced, the HttpException class create a conflict with the [PECL Http extension](http://www.php.net/manual/en/book.http.php) see the trunk code on the [`svn web viewer`](http://svn.php.net/viewvc/pecl/http/trunk/http_exception_object.c?view=markup). Lazy method will be adding a global namespace delcaration and finding all native php classe and prefixing them by `\`

**Comment by bobthecow** [comment]
Thanks for catching that. It's been fixed in `develop`, so it'll go in the next release. Most likely tonight.

**Comment by ludofleury** [comment]
Wow, you we're fast. Thanks, appreciate.

**Comment by bobthecow** [comment]
No problem!

Version 1.4.0 has been released, with newly-namespaced PHP classes, better (and prettier) document folding, and a few other tweaks. Enjoy!
