### ISSUE TITLE
Still not able to connect to MongoHQ hosted databases after 2.3.0

### ISSUE THREAD

**Issue by ygbr** [bobthecow/genghis#100]
Hi,

I have a MongoHQ hosted database (MongoDB 2.4.1) (large) and I still can't connect using the standard dsn:

user:pass@server:port/database

I always get the following error:

Connections error: unauthorized

I have also tried adding the mongodb:// prefix to the URI but it changes nothing.

I have bson_ext installed and I'm running the latest 2.3.0 on Mac OS X 10.8.3

**Comment by bobthecow** [comment]
Do you have special characters in any of the DSN chunks that need to be URI escaped?

**Comment by ygbr** [comment]
not really... my username an password are all alphanumeric standard chars...

**Comment by elia** [comment]
I seem to have the same problem with mongolab.com, like if tries to get admin access

**Comment by bobthecow** [comment]
Is it possible you're running into the same issue as Meteor hosted mongo instances have?

See #102

**Comment by elia** [comment]
@bobthecow don't think so, the password is static

**Comment by jcurtis** [comment]
Same issue here (MongoLab), was just working fine in 2.3.0 mere minutes ago.

**Comment by bobthecow** [comment]
@jcurtis So v2.3.0 was working with MongoLab, and now it's not? Or now v2.3.1 isn't?

**Comment by jcurtis** [comment]
Yes v2.3.0 was working with MongoLab, then I did a `gem update` to bring Genghis up to v2.3.1 plus dependency updates. After that there were authentication errors when trying to connect to the database.

Bonus: I downgraded Geng to v2.3.0 and there are still authentication errors leading me to believe it's a problem with one of the dependencies I updated.

**Comment by bobthecow** [comment]
@jcurtis That's great to know. Do you happen to still have that terminal window open so you can see what updated? Do you mind checking what versions of `bson`, `bson_ext`, `mongo` and `sinatra` gems you were last using?

```
gem list | grep 'bson\|mongo\|sinatra'
```

**Comment by jcurtis** [comment]
```
bson (1.8.5, 1.8.4, 1.8.2, 1.7.1)
bson_ext (1.8.5, 1.8.2)
mongo (1.8.5, 1.8.2, 1.7.1)
sinatra (1.4.2, 1.3.4)
sinatra-contrib (1.4.0, 1.3.2)
sinatra-mustache (0.1.0, 0.0.6)
```

Looks like they we're all updated when I did the upgrade.

**Comment by bobthecow** [comment]
Thanks. I'll dig into this when I get a minute.

**Comment by bobthecow** [comment]
This works:

```
bson (1.8.2)
mongo (1.8.2)
sinatra (1.3.4)
sinatra-contrib (1.3.2)
sinatra-mustache (0.1.0)
```

This works:

```
bson (1.8.2)
mongo (1.8.2)
sinatra (1.4.2)
sinatra-contrib (1.4.0)
sinatra-mustache (0.1.0)
```

... so the latest versions of all dependencies besides bson and mongo work just fine. 

This works:

```
bson (1.8.5)
mongo (1.8.2)
```

And that's the latest version of every gem except `mongo`. I.e., it's gotta be the `mongo` gem.

This works:

```
mongo (1.8.3)
```

But this fails!

```
mongo (1.8.4)
```

So something changed in v1.8.4 of the `mongo` gem which is keeping us from connecting to MongoHQ databases.

Thanks for pointing me in this direction, @jcurtis 

I'll keep digging :)

**Comment by bobthecow** [comment]
The result of the Mongo uri parser changing unexpectedly in `1.8.4`. [This commit](https://github.com/mongodb/mongo-ruby-driver/commit/6428bf699697dbd93622e0a411b5b153295bfe4e#L2R288), specifically.

Hooray SemVer!

I'm releasing a workaround in `v2.3.4` — out later this afternoon — but the real fix is to expect the `mongo` gem to make backwards compatiblity breaks in point releases and start requiring an explicit version for Genghis. I hate to do it, but this — and several past issues — really leaves me no choice.

**Comment by bobthecow** [comment]
`v2.3.4` has been released. Please upgrade and check it out!

**Comment by jcurtis** [comment]
![image](https://f.cloud.github.com/assets/206295/405448/61ce9904-a9db-11e2-8eb3-bf7cd30988f3.png)
Glad I could help. Love the app btw.

**Comment by brndnblck** [comment]
Sorry for the issues here guys. 

This read-only method on MongoClient is actually not documented publicly and was intended primarily for internal use which is why we mistakenly made the change in that version, but the fact that it's not marked private makes that all a moot point. It shouldn't have happend. :-/

**Comment by bobthecow** [comment]
@jcurtis Thank you :)

@brandonblack No worries, this sort of thing happens. Thanks for everything you and the rest of the driver team do.
