### ISSUE TITLE
In 2.3.1 collections with backslashes aren't accessible

### ISSUE THREAD

**Issue by heruan** [bobthecow/genghis#103]
I use PHP namespaces as collection names (e.g. `My\Namespace`). With 2.3.0 I was able to access collections with backslashes in their names, now with 2.3.1 I get a 404 Not Found.

**Comment by bobthecow** [comment]
Thank you for the bug report. This should be fixed in the `develop` branch now. Do you mind taking a look?

**Comment by bobthecow** [comment]
The fix has been released in `v2.3.2`. Thanks again :)
