### ISSUE TITLE
Object has no method 'thunkId' 

### ISSUE THREAD

**Issue by kriswallsmith** [bobthecow/genghis#105]
I'm getting this error while running the latest with all submodules up to date.

https://github.com/bobthecow/genghis/blob/master/src/js/genghis/json.js#L572

**Comment by bobthecow** [comment]
Ooh. Sorry 'bout that. That's what I get for refactoring: 2a9ff168c5b39bed6bd2e4aedb1db864ef404ca0

That's also what I get for playing fast and loose with prototype methods :-/

**Comment by bobthecow** [comment]
Thanks for reporting this. It's fixed in `v2.3.3` :)
