### ISSUE TITLE
Search using an ISODate will only work on first submission

### ISSUE THREAD

**Issue by arthurdarcet** [bobthecow/genghis#106]
When searching with a query like `{time: ISODate("2013-04-23T15:37:06+02:00")`} the results are perfectly ok ; but once the query is complete the search field gets modified to `{time:ISODate("Tue Apr 23 2013 15:36:06 GMT+0200 (CEST)")}` which isn''t a valid query anymore.

Thanks for this great piece of software !
Arthur

**Comment by bobthecow** [comment]
Hmm. [I fixed a problem like this in v2.3.1](https://github.com/bobthecow/genghis/blob/master/CHANGELOG.markdown#v231)... are you using the latest version of Genghis?

I am unable to reproduce this on either the Ruby or PHP backend.

What Genghis version, Ruby/PHP version, browser (and version), and OS (and version) are you running?

Thanks!

**Comment by arthurdarcet** [comment]
Yep, sorry, i am on 2.3.0.

You're too quick, i didn't even think to check for an update since i seted up my system two weeks ago…

Thanks !

**Comment by bobthecow** [comment]
Heh. Yeah, there have been four releases since then.

To be fair, two of them were bugfixes though :)
