### ISSUE TITLE
Allow emptying a collection

### ISSUE THREAD

**Issue by internalfx** [bobthecow/genghis#107]
It would be nice if you could empty a collection without removing it, to keep the indexes and such.

**Comment by bobthecow** [comment]
:+1:

**Comment by bobthecow** [comment]
I haven't yet implemented this, because [it's not very performant on large collections](http://docs.mongodb.org/manual/core/delete/#id1). I'm thinking I'll fake it by dropping the collection then re-creating all the indexes on a new collection. Sound reasonable?

**Comment by bobthecow** [comment]
I've implemented API support for truncating by dropping a collection then recreating its indices. It seems to work well. I'll work it into the UI and get it in the next point release.

**Comment by bobthecow** [comment]
This has been implemented and will appear in the next point release (v2.6.0)

**Comment by bobthecow** [comment]
(Just kidding, v2.4.0)
