### ISSUE TITLE
Unable to delete malformed DSN (empty) server from list

### ISSUE THREAD

**Issue by andrewryno** [bobthecow/genghis#108]
It will delete but upon refresh it will reappear.

Possibly disallow empty values?

**Comment by bobthecow** [comment]
Thanks for reporting this. I'll get a fix into the next release.

**Comment by bobthecow** [comment]
Okay. This has been fixed in `develop`. And it'll even clean up your old broken entry while it's at it :)

**Comment by bobthecow** [comment]
And released. Thanks again!
