### ISSUE TITLE
Can't remove servers, can't view servers, 404: Server Not Found 

### ISSUE THREAD

**Issue by scalascope** [bobthecow/genghis#110]
DSN like test:test@localhost/test
Remove server then reload page, server appear again. 
When I try to view collections, it says 404: Server Not Found.

genghis works through nginx php-fpm

**Comment by bobthecow** [comment]
Are you using the latest version of Genghis?

This is consistent with a problem Apache + mod_php users tend to have, where Apache messes up URI encoded slashes by default. Is it possible your nginx settings are doing something similar?

**Comment by bobthecow** [comment]
Does the slug of that server (the bit that shows up in the URL after `/servers/`) look sane? It should be a URI encoded version of `test@localhost/test`, e.g. `test%40localhost%2Ftest`.

**Comment by scalascope** [comment]
I am using latest version. 
/servers/test%40localhost%2Ftest

**Comment by scalascope** [comment]
nginx config

```
server {
    root /Projects/genghis;
    location / {
        auth_basic "Restricted";
        auth_basic_user_file  /opt/genghis_passwd;
        fastcgi_pass 127.0.0.1:9000;
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/genghis.php;
        fastcgi_param SCRIPT_NAME /genghis.php;
        fastcgi_param PATH_INFO $uri;

        rewrite /genghis.php / permanent;
    }
}
```

**Comment by scalascope** [comment]
Errors do not appear with php built-in web server.

**Comment by bobthecow** [comment]
Fair enough.

If anyone is an nginx wizard, it would be cool to get an updated sample config that can deal with this :)

**Comment by oloflarsson** [comment]
@scalascope I just bumped into this issue and I do not feel like using the internal web server. For me this bug is an issue.

**Comment by bobthecow** [comment]
@oloflarsson I agree, I just don't know enough about nginx configuration to tell you how to fix it. It's most likely related to this though: http://stackoverflow.com/questions/8264239/nginx-unescapes-2f-to-a-forward-slash-how-can-i-stop-it

I'm assuming you're using nginx, right?

**Comment by oloflarsson** [comment]
@bobthecow I'm actually using apache and not nginx.

**Comment by bobthecow** [comment]
@oloflarsson In that case, check the [Apache configuration](https://github.com/bobthecow/genghis/wiki#apache-configuration) section of the wiki. You probably need to change your `AllowEncodedSlashes` setting.

**Comment by oloflarsson** [comment]
Oh I missed that part. Could it not be made part of the .htaccess somehow? That way the risk of other people missing it will be reduced. EDIT: I just found out it cannot. For some reason changing it from .htaccess is not allowed.

**Comment by bobthecow** [comment]
Yeah, unfortunately that needs to be changed in your server or virtual host config.

**Comment by bobthecow** [comment]
I'm planning to rework the server configuration and URLs in the next major release to keep this from biting people. I'm leaning toward using something like `user~host~db` instead of `user@host/db` for the server slug, which saves us from the encoding issue entirely.
