### ISSUE TITLE
Incompatible versions for gem 'Sinatra'

### ISSUE THREAD

**Issue by henry74** [bobthecow/genghis#112]
When trying to install genghis with Padrino 0.11.1 I get the following dependency error:

Bundler could not find compatible versions for gem "sinatra":
  In Gemfile:
    genghisapp (>= 0) ruby depends on
      sinatra (~> 1.3.3) ruby

```
padrino (= 0.11.1) ruby depends on
  sinatra (1.4.2)
```

Any ideas why 1.4.2 wouldn't be accepted for genghisapp?

Thanks,
Henry

**Comment by bobthecow** [comment]
Because it doesn't currently work with 1.4.2 :)

Some things changed in Sinatra 1.4 that I haven't had time to update for yet.

**Comment by henry74** [comment]
If you can point me at the right files, I'll take a look and see if I can make the updates in a fork.

**Comment by bobthecow** [comment]
This has been fixed in `develop` and will be in the next release.
