### ISSUE TITLE
Edit document not work

### ISSUE THREAD

**Issue by mimic2300** [bobthecow/genghis#123]
When you edit the document and did not create any change, it displays "Error updating document." (after click on "Save")
And if you create a change and it displays the same error (JSON syntax is correct).
My version Genghis is 2.3.6 and mongoDB 2.4.5

**Comment by bobthecow** [comment]
Which Genghis backend? Which Mongo driver version? Can you give me an example of a document which doesn't save, or does this happen with all documents?

**Comment by mimic2300** [comment]
It happens with every document. It's not editing and deleting. But the creation of works.
Genghis is 2.3.6
PHP 5.4.4
mongoDB 2.4.5
PHP mongo module 1.3.2rc1 (https://github.com/mongodb/mongo-php-driver/downloads)

What am I doing wrong?

**Comment by bobthecow** [comment]
Are you using PHP with Apache, Nginx, standalone, or other?

**Comment by mimic2300** [comment]
Im using IIS8

**Comment by bobthecow** [comment]
Ah. To be honest, I've never tested Genghis with IIS, so it's amazing that it actually (at least mostly) works :)

Do you mind running the app standalone to ensure that it works that way?

```
php -S localhost:8000 genghis.php
```

**Comment by mimic2300** [comment]
Evening or tomorrow cast a demo and send link ;)
What kind of using a module for PHP (for Windows)? I found this 1.4.1 (http://pecl.php.net/package/mongo), but is not compiled for windows :(

**Comment by mimic2300** [comment]
Little OT... and do you can disable mandatory file name for genghis? I wanted to rename genghis to index and then it did not work :/

**Comment by jmikola** [comment]
@mimic2300: See the [installation instructions](http://us2.php.net/manual/en/mongo.installation.php#mongo.installation.windows). We host pre-compiled Windows binaries on S3.

**Comment by bobthecow** [comment]
@mimic2300 It does work as index.php, you just have to go to `/index.php` in your browser :)

It has to do with how Genghis tries to make clean URLs... it's probably possible to set up URL rewrites in IIS to make it work without the index.php, but I don't know enough about IIS to do it.

The equivalent settings for Apache and nginx are [on the project wiki](https://github.com/bobthecow/genghis/wiki). If you can translate that into IIS URL rewrites, you can name Genghis whatever you want.

**Comment by mimic2300** [comment]
@jmikola I tried different versions of the mongo for a version 1.4.x in PHP (or genghis) not working. (now i use 1.3.7 for PHP 5.4.4)

@bobthecow Here are examples... 
1) http://db.ophite.cz/mongo/m1/genghis.php
2) http://db.ophite.cz/mongo/m2/ (This is how it looks when you do not have written this URL "index.php" (with him it works). The footer is loaded, but the rest did not.)

Try to have something to add, remove, edit and you will see that it does not: (
When you take something, so disappear, but when you put refresh, so it's back there.

**Comment by mimic2300** [comment]
OT... May I ask when is the next version, which would add permissions to read / write or login below to DB auth? (as it has to be client MongoExplorer)
Otherwise I like this app :)

**Comment by bobthecow** [comment]
1) I think I've found your problem. More info in a minute.

2) This is what I was saying. In the Apache or nginx configs I linked above, we rewrite all URLs to include the script name, e.g. http://db.ophite.cz/mongo/m2/assets/script.js?v=2.3.6 to http://db.ophite.cz/mongo/m2/index.php/assets/script.js?v=2.3.6 and http://db.ophite.cz/mongo/m2/servers to http://db.ophite.cz/mongo/m2/index.php/servers

This is why m2 works if you put index.php at the end, but it doesn't work if you just use http://db.ophite.cz/mongo/m2/

It's possible to configure URL rewrites on IIS as well. If you can figure out the settings, you can name your script index.php :)

**Comment by bobthecow** [comment]
It looks like your problems editing and deleting are directly related to rewriting URLs on IIS. GET and POST requests to /genghis.php/foo/bar work just fine, but PUT and DELETE requests do not. They are returning 404. This means that Genghis is unable to edit or delete documents, collections and databases.

I think the answer for you is to set up URL rewrites with IIS. A quick search found this:

http://www.iis.net/downloads/microsoft/url-rewrite

... and it looks like it'll do just what we need. Specifically, we need an inbound URL rewrite something like this:

``` xml
<rule name="Rewrite to genghis.php" stopProcessing="true">
    <match url="^(.*)" />
    <conditions trackAllCaptures="true">
        <add input="{QUERY_STRING}" pattern="^(.*)" />
    </conditions>
    <action type="Rewrite" url="genghis.php/{R:1}?{C:1}" />
</rule>
```

Note that I don't have an IIS server to test this on, but it should look something like that. I'd be very grateful if you could contribute your findings to the wiki so future users can run Genghis on IIS as well :)

**Comment by bobthecow** [comment]
Also, I don't know when the next version is :)

Specifically, are you looking for read-only authentication support, or something else?

**Comment by mimic2300** [comment]
I try to play with then rewrite and I'll see :)

Top that only authorized users can connect to its own DB.
Genghis me after the administration side likes but for clients is unusable if every client has their own database :(

**Comment by bobthecow** [comment]
Genghis already does support per-database authentication. Use:

```
user:pass@host:12345/db
```

**Comment by mimic2300** [comment]
Your rewrite not work  (error 404 for all pages). If i put Genghis into the main directory so displays works, but still does not work edit/delete :(

"user:pass@host:12345/db" yes, that know, but this is only add new connection to DB, and connections can add anyone (anyone add connection to localhost = new admin). You know what I mean right?

**Comment by bobthecow** [comment]
I figured my rewrite wouldn't work. I coded it up by hand and don't even have an IIS server to test it on. But it should be _something_ like that, because that's how rewrites work for nginx and apache :)

I'm not sure what you mean.
