### ISSUE TITLE
Password with @ char

### ISSUE THREAD

**Issue by heruan** [bobthecow/genghis#125]
I'd like to use `genghis` to connect to a Mongo database. I got my credentials, but the password contains an `@` char. When I try to add the DSN on `genghis` dashboard in the form `user:password@hostname` using `%40` for the `@` char it fails to connect.

P.S. Unfortunately I cannot request a new password by now.

**Comment by bobthecow** [comment]
Thanks for reporting. I'll take a look.

**Comment by bobthecow** [comment]
This appears to be a bug in the MongoClient URI parser. Here's the Ruby version:

``` rb
auth = Mongo::URIParser.new('mongodb://foo:b%40r@localhost/admin').auths.first
auth[:password]

# => 'b%20r'
```

Compared to creating the auth directly:

``` rb
auth = Mongo::MongoClient.new.add_auth('admin', 'foo', 'b@r', nil)
auth[:password]

# => 'b@r'
```

Connecting via the URI doesn't work, but the direct auth does. And the same thing in PHP:

``` php
$m = new MongoClient('mongodb://foo:b%40r@localhost/admin');

// => MongoConnectionException with message 'Failed to connect to: localhost:27017:
//    Authentication failed on database 'admin' with username 'foo': auth fails'
```

I'll file a bug with 10gen, but your best bet for now is to try to get your password changed :-/

**Comment by bobthecow** [comment]
I created [an issue for the Ruby driver](https://jira.mongodb.org/browse/RUBY-657). It looks like there's already [an open issue for the PHP driver](https://jira.mongodb.org/browse/PHP-416?focusedCommentId=395623#comment-395623).

Searching their issue tracker, it looks like it's a common problem [across](https://jira.mongodb.org/browse/CSHARP-469) [most](https://jira.mongodb.org/browse/PYTHON-319) [drivers](https://jira.mongodb.org/browse/PERL-130).

Feel free to :+1: any of those issues :)

**Comment by TylerBrock** [comment]
As an update, the fix for this issue is in 1.x-stable and it will be in the next Mongo Ruby Driver release (1.9.2).

**Comment by bobthecow** [comment]
Thanks for the quick fix, @TylerBrock
