### ISSUE TITLE
Genghis 2.3.7 is detected as 2.3.6

### ISSUE THREAD

**Issue by ghost** [bobthecow/genghis#127]
After installing Genghis 2.3.7 the following message appears:

A Genghis update is available
You are running Genghis version 2.3.6. The current version is 2.3.7. Visit genghisapp.com for more information.

**Comment by bobthecow** [comment]
Are you running the Ruby backend? If so, can you run `genghisapp --kill` then restart to see if it fixes it?

**Comment by ghost** [comment]
Oh, I'm very sorry. gem install installed an older gem, 2.3.6. The message was correct.

**Comment by bobthecow** [comment]
Heh. That'll do it :)
