### ISSUE TITLE
Using gem with nginx and unix socket

### ISSUE THREAD

**Issue by maxvipon** [bobthecow/genghis#134]
Is there a way to somehow configure gem and use It with unix socket instead 0.0.0.0:5678 and nginx as proxy?

**Comment by bobthecow** [comment]
Yes. Not just one, but _many_ ways :)

One example, using Thin:

Add this `Gemfile` to a project folder:

``` rb
source 'https://rubygems.org'
gem 'genghisapp'
gem 'thin'
```

And this `config.ru`:

``` rb
require 'genghis'
run Genghis::Server
```

Run `bundle install` to install all dependencies.

You'll start Genghis like this:

``` bash
bundle exec thin start -R config.ru --socket /tmp/genghis.sock
```

How exactly you start and keep Genghis running depends very much on your system, but you might use `monit` or `god` or some `init.d` script or something.

Now point Nginx to `/tmp/genghis.sock` and you're set!
