### ISSUE TITLE
Can't find variable: GenghisDate

### ISSUE THREAD

**Issue by rtorcato** [bobthecow/genghis#135]
get this error when i try to insert document with date: "joinedDate" : Date( 1353168028000 )

**Comment by bobthecow** [comment]
You should use ISODate instead :)

I'll try to make that error go away though.

**Comment by rtorcato** [comment]
cool thanks

**Comment by bobthecow** [comment]
This should be fixed in `develop`. Do you mind giving it a spin?

I tested it with this document:

``` js
{
    a: Date(1378240369000),
    b: new Date(1378240369000),
    c: Date("2013-09-03T13:32:49-07:00"),
    d: new Date("2013-09-03T13:32:49-07:00"),
    e: ISODate("2013-09-03T13:32:49-07:00"),
    f: new ISODate("2013-09-03T13:32:49-07:00")
}
```

... and all of 'em work now :)

**Comment by bobthecow** [comment]
I'm assuming that's a yes. Feel free to reopen this issue if it didn't work for you :)

**Comment by rtorcato** [comment]
sorry yes it was fixed. Thanks
