### ISSUE TITLE
 'safe' option is deprecated

### ISSUE THREAD

**Issue by rtorcato** [bobthecow/genghis#137]
Using mongoclient instead of mongo I get when trying to delete document:

PHP error: MongoCollection::remove(): The 'safe' option is deprecated, please use 'w' instead

similar errors for updates and inserts.

**Comment by bobthecow** [comment]
Are you using a HEAD install of the PHP MongoDB driver?

**Comment by rtorcato** [comment]
it's latest version. https://github.com/mongodb/mongo-php-driver

they updated to mongoclient awhile ago http://derickrethans.nl/mongoclient.html

**Comment by bobthecow** [comment]
Yeah, but they didn't start with the deprecation warnings until _after_ the current released version, iirc. Did you install from source? Or are you seeing that error with a released version of the driver?

**Comment by rtorcato** [comment]
this is the driver i am using: curl https://codeload.github.com/mongodb/mongo-php-driver/zip/master > mongo-php-driver-master.zip

**Comment by bobthecow** [comment]
Gotcha. That's an unreleased version with a backwards compatibility break. As usually.

I'll get a fix out by the time it's released :)

**Comment by rtorcato** [comment]
ah ok. Ya I was having a hard time trying to get mongo extension to install on bitnami lamp stack and had to use curl to install the zip. I guess I should've paid more attention to the issues with that version. It's a dev server anyway. So not a big deal on my side.

thanks for the quick replies.

**Comment by bobthecow** [comment]
you might(?) be able to get the warnings to go away by changing the PHP error level for that server or app. give it a shot and let me know if it works?

**Comment by rtorcato** [comment]
hmm changed the php error level but it didn't work.

**Comment by bobthecow** [comment]
@rtorcato Mind giving the `develop` branch version a try? It should be fixed.

**Comment by rtorcato** [comment]
hey it works….great job! thanks

**Comment by bobthecow** [comment]
no problem. i'll close this issue, but it likely won't be released until either the next version of the driver ships, or Genghis ships v2.4.

**Comment by bobthecow** [comment]
This has been released in v2.3.9.

**Comment by demorf** [comment]
I get the same error with the latest version of the driver and latest version of mongoDB on windows 7.
