### ISSUE TITLE
undefining `object_id' 

### ISSUE THREAD

**Issue by anand9** [bobthecow/genghis#139]
I am using Rails 3, when i add 

``` ruby
   require 'genghis'
```

in routes i am getting this when i start my server with rails c

``` ruby
/gems/ruby-1.9.3-p392/gems/genghis-1.4.1/lib/genghis.rb:268: warning: undefining `object_id' may cause serious problems
```

also i get the error 

``` ruby
    uninitialized constant Genghis::Server (NameError)
```

**Comment by bobthecow** [comment]
That's because you installed [the `genghis` gem](http://rubygems.org/gems/genghis), not `genghisapp`.

**Comment by anand9** [comment]
oh sorry i got confused

**Comment by bobthecow** [comment]
No worries :)
