### ISSUE TITLE
Support connecting to replicasets

### ISSUE THREAD

**Issue by taxilian** [bobthecow/genghis#14]
It would be great if it were possible to connect to a mongodb replicaset.

**Comment by bobthecow** [comment]
Great idea. I'll gladly accept a pull request. Otherwise, I'll add it to my queue :)

**Comment by bobthecow** [comment]
@taxilian Do me a favor and test the `develop` version? It should be good to go. Connect like this:

```
localhost:12345/?replicaSet=foo
```

**Comment by taxilian** [comment]
So I'm looking at the php connection stuff and what you're suggesting and it doesn't even look at all similar to what I'm using in node.js; to connect to a replicaset using node we specify a list of servers like this:

mongodb://server1.com:27017,mongodb://server2.com:27017

In addition we add a database name.  Since the server I'm running PHP on and the server running mongo aren't the same, I dont' even know where to start trying to figure out what the name of a replicaSet that I should be setting is or why the computer would know that.

Every attempt I've made to add the servers has resulting in a "Notice: Undefined variable: name in /Users/richard/Sites/genghis/genghis.php on line 12" and a not found error with no visible error message on the UI; theoretically if I connect to one part of the replicaset it might get the list and set things up correctly from there.

Is this a bug elsewhere?

**Comment by bobthecow** [comment]
Gotcha.

There are two ways of connecting to replica sets. One is with comma separated hosts, the other is with one or more hosts plus a replica set name.

According to [the docs on connections](http://www.mongodb.org/display/DOCS/Connections), the standard URI format is:

```
mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
```

It's not yet supported by all drivers, but this is what Genghis is trying to use :)

So in your case, it would be

```
mongodb://server1.com:27017,server2.com:27017/yourDbName
```

(note that there's only one scheme, and it has a trailing slash + db name) ... Genghis should be able to use that style without modification.

What I just implemented support for was the named replica set version, which would use:

```
mongodb://server1.com:27017/yourDbName?replicaSet=someName
```

**Comment by taxilian** [comment]
so, as I learn more about how this works... yeah, it all works fine.  good work. :-P

**Comment by taxilian** [comment]
(as a note to future users, many replicasets you can just connect to whichever server is the primary and it'll end up working)

**Comment by bobthecow** [comment]
:+1: awesome :)
