### ISSUE TITLE
Unable to input longs

### ISSUE THREAD

**Issue by ghost** [bobthecow/genghis#142]
Modifying a document specifying, for instance, NumberLong(123) as value, fails.

**Comment by bobthecow** [comment]
Yeah, it looks like Genghis doesn't have 64 bit integer support built yet.

Are you using the PHP or Ruby backend?

**Comment by bobthecow** [comment]
Cool. I'll work on this when I get a minute, but that could take a week or two.

**Comment by bobthecow** [comment]
@partycoder Are you using 32 or 64 bit ruby?

**Comment by bobthecow** [comment]
Fair enough. It should now be fixed for both, regardless :)

**Comment by arboreal84** [comment]
It seems this is now fixed, so closing.
