### ISSUE TITLE
Installation in windows for sails

### ISSUE THREAD

**Issue by hasnainmcs** [bobthecow/genghis#144]
How to install genghisapp in windows ?
i wana to use it on my sails.js framework ..
which command work for windows ?

http://sailsjs.org/#!

**Comment by bobthecow** [comment]
The best way to run on Windows is probably running Genghis.php under WAMP.

**Comment by hasnainmcs** [comment]
![capture](https://f.cloud.github.com/assets/3217075/1449359/bee552c0-4267-11e3-87f4-b560a7836d37.JPG)

Thanks for your response ..
i am facing that issue after installation monogdb by this command "npm install sails-mongo" after that when i start db by this command "monogod" its no work and when i start the server then its show error like image that i attache ..

my local.js is like that ..

 environment: process.env.NODE_ENV || 'development',

 adapters:{

```
'default': 'mongo',

mongo: {
  module: 'sails-mongo',
  host: 'localhost',
  database: 'test',
  schema: true,

  user: '',
  paswsword: ''
},

  }
```

**Comment by calvertyang** [comment]
[sails-mongo](https://github.com/balderdashy/sails-mongo) just MongoDB adapter for Sails.js, if you want to install MongoDB on windows, please reference [Install MongoDB on Windows](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-windows/)

**Comment by bobthecow** [comment]
I'm not entirely sure what any of this has to do with Genghis...

**Comment by calvertyang** [comment]
I think hasnainmcs misunderstanding Genghis's purpose.

[Sails.js](https://github.com/balderdashy/sails) is realtime MVC framework for Node.js and nothing to do with Genghis.

**Comment by bobthecow** [comment]
@hasnainmcs:
- MongoDB is a database server. To use MongoDB in any form, you must install a MongoDB server (see the link @CalvertYang posted earlier).
- Sails.js is a framework for Node.js. sails-mongo is an adapter to get Sails.js to talk to the MongoDB server you installed in the first bullet point.
- Genghis is a MongoDB admin app. It has nothing to do with Sails.js or sails-mongo. It _also_ talks to the MongoDB server you installed in the first bullet point.

**Comment by hasnainmcs** [comment]
CalvertYang : 
i already install mongoDb packeg by this command "npm install sails-mongo" ..
i am doing same as it like that youtube toturial ..
www.youtube.com/watch?v=G4-fm_h8z-0‎
in this toturial he install mongo by making local.js ..
i do same as it is after installation when i run command "mongod" for starting database then its not work ..
and when i start the server then it show same error as image ..
when i remove 'default': 'mongo'  from my adapter then its work fine but this time it not used mongo db ..
leave for now genghisapp but need to fix first monogdb ..

in this video everything works fine when i do same like that then it shows that error .
i don't understand what i need to fix for this error ..

when i remove this works fine 
adapters:{

'default': 'mongo',

mongo: {
  module: 'sails-mongo',
  host: 'localhost',
  database: 'test',
  schema: true,

  user: '',
  paswsword: ''
},

  }

and  when i add then same error .

**Comment by hasnainmcs** [comment]
bobthecow : 
you can see in this toturial Ep: 11 he used genghisapp for view database and management .. 

but before using genghisapp we need to run  monogDB first ..

**Comment by bobthecow** [comment]
`npm install sails-mongo` does _not_ install MongoDB.

It just installs something so that Sails.js can talk to MongoDB.

You can't run `mongod` because you still haven't installed MongoDB.

**Comment by bobthecow** [comment]
If you look at that tutorial, he types `npm install sails-mongo` in his terminal window at 2:00. Pause it and look at the other tab. He's running `mongod` in the next tab. He already has MongoDB installed, but doesn't cover installation in that tutorial.

[Install MongoDB using these instructions](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-windows/)

**Comment by calvertyang** [comment]
@hasnainmcs:

The command `npm install sails-mongo` **only** install MongoDB adapter for Sails.js

You need to **[install MongoDB first](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-windows/)**, so that Sails.js can connect to MongoDB via sails-mongo

**Comment by ricardocarvalh0** [comment]
After installing MongoDB you need to add MongoDB directory to the environment variables, so that you can run 'mongod' at windows prompt. After running 'mongod', open an other prompt and run your sails app.
