### ISSUE TITLE
Unable to delete server from list

### ISSUE THREAD

**Issue by calvertyang** [bobthecow/genghis#145]
I got 404 error when remove server from list, is there any other way can remove server from list?

My genghis is Version 2.3.8 and starting by execute command `genghisapp`

![2013-11-03 12 51 43](https://f.cloud.github.com/assets/898040/1459501/6ec36484-43df-11e3-9fc2-0c47f86a5d1a.png)

**Comment by bobthecow** [comment]
That's weird. It looks like it's trying to delete `/servers`, not `/servers/$serverid` (but it is a bit hard to tell from your screenshot). Can you confirm for me?

**Comment by calvertyang** [comment]
I tried two situation as follow:
1. Add server: **user@localhost:27017/test**
   Result: Remove from list successful
   
   ![2013-11-03 10 04 21](https://f.cloud.github.com/assets/898040/1460358/825f9cd0-442d-11e3-83a7-728c66e6758d.png)
2. Add server: **user:pass@localhost:27017/test**
   Result: Cannot remove from list
   
   ![2013-11-03 9 58 11](https://f.cloud.github.com/assets/898040/1460357/7f545c74-442d-11e3-9eaa-4bf7a084148a.png)

If i add a server that has password, it cannot remove from list.

Hope these information can help you to find out the issue, feel free to tell me if you need any further information.

**Comment by bobthecow** [comment]
That is quite strange. Both are deletable for me.

What is the output of `ruby --version` and `genghisapp --version` for you?

**Comment by calvertyang** [comment]
ruby --version

```
ruby 1.9.3p448 (2013-06-27 revision 41675)
```

genghisapp --version

```
'genghisapp' 2.3.8
rack 1.2
sinatra 1.4.4
vegas 0.1.11
```

BTW, my ruby is installed by rvm.

**Comment by bobthecow** [comment]
When you run `genghisapp` is it running your rvm version of ruby?

**Comment by calvertyang** [comment]
Oops, I found the reason that why I cannot delete the server from list.

The browser cache let me misunderstanding the server still on the list, but it has been deleted.

Thanks for your help.

**Comment by bobthecow** [comment]
Cache is also a problem, as Genghis should be preventing the browser from caching _anything_ :)

**Comment by calvertyang** [comment]
That's really strange. I found that after I add a server, and than clear the browser cookie, the server is disappear from the list.

I think the server doesn't added from the beginning, but I'm sure the connection information is correct and the remote mongodb is running.

**Comment by JoeyHoutenbos** [comment]
I had the same problem. The caching was indeed the problem.
After deleting the cookie the servers where removed...

PS: I am using the PHP version
