### ISSUE TITLE
Adding Authentication?

### ISSUE THREAD

**Issue by cmpsoares91** [bobthecow/genghis#154]
Can't figure out how to protect Genghis with user and password... :-S

Is this even possible? Could be a nice feature though!

**Comment by bobthecow** [comment]
The easiest way is to configure your server to use HTTP Basic Auth. Instructions for that vary depending on what sort of server you're using. If you're using Ruby, a `config.ru` file like this would do the trick:

``` rb
require 'genghis'

use Rack::Auth::Basic, 'Genghis' do |u, p|
  u == 'admin' && p == 'hunter2'
end

run Genghis::Server
```

Then run it with `rackup` instead of `genghisapp`.
