### ISSUE TITLE
Can't delete server that has a ?

### ISSUE THREAD

**Issue by sb8244** [bobthecow/genghis#157]
PHP Version - Latest

Case: 
1. Add server like server.com?replicaSet=rs0
2. Add another server like server.com
3. Remove server.com?replicaSet=rs0
4. server.com is removed and replicaSet one remains

**Comment by bobthecow** [comment]
That's strange. You can definitely delete it by clearing your cookies, if nothing else.

It might be a URL encoding issue. Are you running behind Apache? Does using the "?" server work otherwise? Can you browse to its databases?
