### ISSUE TITLE
Cannot connect to any server

### ISSUE THREAD

**Issue by jakubp** [bobthecow/genghis#158]
Hi :)

I installed Genghis on my computer today (main branch). I use PHP version. I open it in my browser, but localhost or any other server won't connect.

Error message I get: "Failed to connect to: localhost:27017: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

I tried connecting to a MongoHQ server, no luck either. 

I know I can connect to a MongoDB from PHP because my own app works for both localhost and mongoHQ.

I use:
Windows 7 64bit
Apache 2.2
PHP 5.4
PHP Mongo driver 1.4.5

Any suggestions what I can try?

Thanks -
Jakub

**Comment by bobthecow** [comment]
For localhost, try connecting to 127.0.0.1 instead.

**Comment by jakubp** [comment]
Thank you, that worked!

**Comment by bobthecow** [comment]
It seems to be an issue with the Windows hosts file, at least according to #140. Per that comment thread, I think the best course of action is to use `localhost` by default, but if we can't connect to that for some reason, try falling back to `127.0.0.1`.
