### ISSUE TITLE
Genghisapp 2.3.10 fails to start centos 6 after fresh gem install

### ISSUE THREAD

**Issue by cpuchip** [bobthecow/genghis#163]
[michael@localhost ~]$ genghisapp 
/usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require': /usr/lib64/ruby/gems/1.8/gems/sinatra-mustache-0.3.1/lib/sinatra/helpers/mustache.rb:10: syntax error, unexpected tIDENTIFIER, expecting tAMPER (SyntaxError)
          add_to_mustache_helper_methods(*arg.instance_methods, arg)
                                                                   ^
    from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /usr/lib64/ruby/gems/1.8/gems/sinatra-mustache-0.3.1/lib/sinatra/mustache.rb:2
    from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /usr/lib64/ruby/gems/1.8/gems/genghisapp-2.3.10/genghis.rb:870
    from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /usr/lib64/ruby/gems/1.8/gems/genghisapp-2.3.10/bin/genghisapp:9
    from /usr/bin/genghisapp:23:in `load'
    from /usr/bin/genghisapp:23

**Comment by cpuchip** [comment]
I rolled back to 2.3.8 and it starts fine

**Comment by bobthecow** [comment]
It looks like, as of v3.0, `sinatra-mustache` dropped support for Ruby 1.8. Genghis still supports Ruby 1.8, but to use it you'll have to manually install a version of `sinatra-mustache` that works with your system. I don't have a machine to test it on, but this would probably work?

```
gem install sinatra-mustache --version '= 0.2.0'
```

You might need to uninstall any existing `sinatra-mustache` versions you have installed first, so that it'll pick that one?

**Comment by cpuchip** [comment]
looks like sinatra-mustache 0.2.0 still doesn't work.
though rolling all the way back to gem install sinatra-mustache --version '= 0.1.0'
does work. Which is what genghisapp 2.3.8 installed.

I got 2.3.10 working now thank you.

**Comment by bobthecow** [comment]
No problem. Glad you got it working. Since there's not much I can do about the dependency from my end, I'll go ahead and close this issue.
