### ISSUE TITLE
genghisapp : command not found

### ISSUE THREAD

**Issue by pierreburgy** [bobthecow/genghis#168]
Hi !

I recently installed genghis with gem but when I try to launch the app I obtain a "command not found"

Here is my configuration : 
OS X 10.9.2
MongoDB shell version: 2.4.9 (installed with homebrew)
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin13.0](installed with homebrew)
gem version : 2.0.3

Do you know what could be the solution?

Thanks for your help,

Pierre

**Comment by bobthecow** [comment]
Hmm. Your rubygem `bin` path probably isn't in your shell's `$PATH`? Run this:

```
gem environment
```

… and check the `EXECUTABLE DIRECTORY` setting. Make sure it's in your `$PATH`:

```
echo $PATH
```

**Comment by pierreburgy** [comment]
Thanks for your answer, here is the path I obtained : 
/Users/pierreburgy/pear/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

**Comment by pierreburgy** [comment]
RubyGems Environment:
- RUBYGEMS VERSION: 2.2.2
- RUBY VERSION: 2.1.1 (2014-02-24 patchlevel 76) [x86_64-darwin13.0]
- INSTALLATION DIRECTORY: /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0
- RUBY EXECUTABLE: /usr/local/Cellar/ruby/2.1.1/bin/ruby
- EXECUTABLE DIRECTORY: /usr/local/Cellar/ruby/2.1.1/bin
- SPEC CACHE DIRECTORY: /Users/pierreburgy/.gem/specs
- RUBYGEMS PLATFORMS:
  - ruby
  - x86_64-darwin-13
- GEM PATHS:
  - /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0
  - /Users/pierreburgy/.gem/ruby/2.1.0
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - https://rubygems.org/
- SHELL PATH:
  - /Users/pierreburgy/pear/bin
  - /usr/local/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/bin

**Comment by bobthecow** [comment]
Yep. Your path doesn't include the RubyGems `bin` directory. And it looks like you're using Homebrew's Ruby. According to `brew info ruby`, gem executables are added to `/usr/local/opt/ruby/bin`.

Add something like this to `.profile` or `.bashrc` or whatever you use:

``` bash
export PATH=/usr/local/opt/ruby/bin:$PATH
```

**Comment by pierreburgy** [comment]
Thanks a lot, I finally solved the problem using this line which was advised by brew when I used "brew info ruby" : 

sudo gem pristine --all --only-executables

Let's use Genghis !

**Comment by bobthecow** [comment]
:+1:
