### ISSUE TITLE
Config with Server data

### ISSUE THREAD

**Issue by ro-ka** [bobthecow/genghis#17]
I liked to be able to store the connection details in an optional config to not have to enter it every time.

My genghis is restricted in access by http_auth, so it's not a security issue.

I know that this would break the single file mentality, that's why it should be optional.

**Comment by bobthecow** [comment]
Would an environment variable work for you?

```
export GENGHIS_SERVERS='localhost;mongo.example.com:12345'
```

This would maintain the single-file approach while still allowing you configuration. It would also allow configuration via a number of mechanisms (.htaccess, nginx config, rc files, heroku config, etc).

**Comment by ro-ka** [comment]
That would be totally fine. :)

**Comment by bobthecow** [comment]
@ro-ka Do me a favor and test the `develop` branch version? It should be good to go.

**Comment by ro-ka** [comment]
Tested, but I cannot see any servers in the server list. Neither loaded ones nor manually added via the interface. Also the default localhost server wasn't there.

**Comment by bobthecow** [comment]
@ro-ka Sorry about that. I messed up a merge with another change I made to server handling (to support named replica sets). I just pushed a new version which should fix your problem. Check out the `develop` branch again?

**Comment by bobthecow** [comment]
This feature will be in the upcoming v2.0 release. Resolving this issue.

**Comment by ro-ka** [comment]
Sorry, I switched to mongo-express as it was working at the time and doesn't need php. Removed php support from my server that's why I wasn't able to test it.
But thanks for fixing! :)

**Comment by ro-ka** [comment]
But maybe I'll return, as mongo-express currently doesn't offer searching.

**Comment by bobthecow** [comment]
[Good news!](https://github.com/bobthecow/genghis/blob/develop/CHANGELOG.markdown#v200-dev)

(see bullet 2)

**Comment by ro-ka** [comment]
Nice! But my server is currently node.js only  :)

**Comment by bobthecow** [comment]
Heh. A node implementation isn't going to make it in v2.0. Sorry 'bout that :P
