### ISSUE TITLE
@ symbol in password causes a malformed server error.

### ISSUE THREAD

**Issue by harlanhaskins** [bobthecow/genghis#171]
I have an `@`in my password, and cannot think of a way to escape that to avoid the malformed server error when typing in a server address using `user:p@ss@server.tld/collection`

I've tried escaping it (like `\@`) to no avail.

**Comment by bobthecow** [comment]
You have to URL encode it, since it's in a URL :)

`%40`

**Comment by harlanhaskins** [comment]
That...makes a lot of sense. Thanks!

It'd be nice if there was a popup saying to URL encode characters.

**Comment by bobthecow** [comment]
Note that there was a bug in the drivers for both PHP and Ruby at different points where it wouldn't deal very well with URL encoded things in the password. If you run into problems even after encoding it, you should make sure you have an updated driver installed.

**Comment by bobthecow** [comment]
And yes, more help would be helpful :)

I'm thinking putting it in the "malformed url" message would work well, since then it would only show up for people who need it?

**Comment by harlanhaskins** [comment]
That'd be great! Just check if they have any of the disallowed URL characters (or more than 1 `@`) and advise them to url encode. That'd be really nice.
