### ISSUE TITLE
Feature request - allow non ObjectId search

### ISSUE THREAD

**Issue by cyberwombat** [bobthecow/genghis#179]
Right now the search field assumes ObjectId indexes - but it's possible to use uuids or other. I personally use Buffer with uuid as my _id. Would be nice to search by that.

**Comment by bobthecow** [comment]
You can search by anything, but the only one that automatically converts to a query is ObjectId. To search by anything else, use a normal MongoDB query object:

``` js
{_id: "Whot!"}
```

**Comment by cyberwombat** [comment]
Lol I had no idea you could search by other things!  sweet
