### ISSUE TITLE
Genghis crashes my Apache install when XCache is activated

### ISSUE THREAD

**Issue by julien-c** [bobthecow/genghis#18]
Hi,

For some reason, Genghis crashes Apache on my dev. machine (OS X Lion, latest version of MAMP, latest Mongo installed from homebrew, and PHP driver from 10gen (`1.0.11`)). 

Any idea why?

**Comment by bobthecow** [comment]
I haven't run into this before. What was the issue?

**Comment by julien-c** [comment]
Apache's not too clear about it:

```
*** set a breakpoint in malloc_error_break to debug
[Fri Jul 06 18:15:35 2012] [notice] child pid 29842 exit signal Abort trap (6)
httpd(29980) malloc: *** error for object 0x10204c188: pointer being freed was not allocated
```

I guess the issue is with the very old driver I'm using (the latest one for Mac OS from https://github.com/mongodb/mongo-php-driver/downloads is two years old), but other Mongo apps I use work well.

I guess I'll have to try building the driver from PECL (though it's a pain in MAMP) -- or just jump straight to production :)

Can't wait to try Genghis though, looks way better than my custom scripts !

**Comment by bobthecow** [comment]
There were some pretty serious bugs with older versions of the Mongo driver, so you're prob'ly better off upgrading anyway :)

**Comment by julien-c** [comment]
Well, I am now proudly running driver version 1.2.10, but that was not it :(

I'll try to explain the issue more precisely: I can see `http://localhost/genghis/` allright (including assets etc.) but Apache crashes when getting `GET http://localhost/genghis/servers`and `GET http://localhost/genghis/servers` (as well as when POSTing a server).

I'm not sure what to try -- any suggestion ?

**Comment by bobthecow** [comment]
Do you have APC or eAccelerator installed?

**Comment by julien-c** [comment]
No, but I had XCache activated. Deactivated it, and it works!

**Comment by julien-c** [comment]
Another strange thing (maybe I should open another issue): I have 404s and empty pages when going into the "detailed" single-document view (e.g. `http://localhost/genghis/servers/localhost/databases/amazon_product/collections/similarities/documents/0060517123`) though I know these documents exist (they're listed in the "list" view, for one).

**Comment by julien-c** [comment]
Not sure why, but this seems to only happen on collections where `id`s were not autogenerated by MongoDB (those are barcode-like natural ids) -- I'll open another issue.
