### ISSUE TITLE
Local installation issue...

### ISSUE THREAD

**Issue by rv-kip** [bobthecow/genghis#182]
I was unable to run genghis locally from a cloned git repo with the instructions in the Readme.  I got this error:

```
Network error while fetching https://rubygems.org/quick/Marshal.4.8/pg-0.17.1-x86-mingw32.gemspec.rz
```

This is what worked for me. `bundler install`, not `bundle install`

```
$ gem install bundler
$ bundler install
$ ruby genghis.rb
```

**Comment by bobthecow** [comment]
Your error was a network error, so retrying it likely fixed the issue. `bundle` == `bundler`, so you very literally just ran the exact same thing.

https://github.com/bundler/bundler/blob/1-6-stable/bin/bundle

https://github.com/bundler/bundler/blob/1-6-stable/bin/bundler

**Comment by rv-kip** [comment]
So they are. Weird. I can consistently repro the behavior...

```
$ git clone https://github.com/bobthecow/genghis.git
$ cd genghis
$ git checkout feature/three-dot-oh-my
$ gem install bundler
$ bundle install
Network error while fetching https://rubygems.org/quick/Marshal.4.8/json-1.8.1-java.gemspec.rz
$ bundle install
Network error while fetching https://rubygems.org/quick/Marshal.4.8/json-1.8.1-java.gemspec.rz
$ bundler install
[Success]
$  which bundle
.../rvm/gems/ruby-1.9.2-head/bin/bundle
$ which bundler
.../.rvm/gems/ruby-1.9.2-head/bin/bundler
```

Oh well. Thanks

**Comment by bobthecow** [comment]
wait. is `bundle` in `/rvm/` or did you typo when you redacted the path?

**Comment by rv-kip** [comment]
Typo. 

```
.../.rvm/gems/ruby-1.9.2-head/bin/bundle
.../.rvm/gems/ruby-1.9.2-head/bin/bundler
```

**Comment by bobthecow** [comment]
Strange. Maybe it's something weird with RVM, or a version mismatch or something? Does `bundle --version` and `bundler --version` return the same thing?

**Comment by rv-kip** [comment]
They both are 1.6.4

```
bundle --version
Bundler version 1.6.4
bundler --version
Bundler version 1.6.4
```

```
diff .../.rvm/gems/ruby-1.9.2-head/bin/bundler .../.rvm/gems/ruby-1.9.2-head/bin/bundle
23c23
< load Gem.bin_path('bundler', 'bundler', version)
---
> load Gem.bin_path('bundler', 'bundle', version)
```
