### ISSUE TITLE
Malformed document

### ISSUE THREAD

**Issue by jzumbrun** [bobthecow/genghis#185]
No matter what I do I cant seem to add a "correct" document.

Some thing a simple as 

```
{
    name: "Jon Zumbrun"
}
```

Doesnt work.
I just keep getting: Malformed document

**Comment by bobthecow** [comment]
It sounds like you might have a webserver configuration issue or something. That shouldn't be a malformed document :)

What backend are you using? What version? Where are you entering that document?
