### ISSUE TITLE
genghis app run at 0.0.0.0:5678 but can not be accessed

### ISSUE THREAD

**Issue by macknight** [bobthecow/genghis#191]
i changed the host to 127.0.0.1, it can be accessed, why?

**Comment by bobthecow** [comment]
Sorry for the delay, I was on vacation :)

Sometimes the browser window launches too fast, and requests the page before the Genghis server has finished booting. If that happens, just refresh the page and it should show up.

**Comment by bobthecow** [comment]
This is probably the same issue as #192… I'll close this one as a duplicate as the other has more info. Feel free to chime in there, or to comment here if it's not the same issue!
