### ISSUE TITLE
PHP 5.6.5 vs genghis v2.3.11

### ISSUE THREAD

**Issue by piengeng** [bobthecow/genghis#200]
@bobthecow hi, I'm running genghis 2.3.11 with PHP 5.6.5, seeing below suggestion, adding 'always_populate_raw_post_data' to php.ini solves the problem. If you have time could you look into this? Just thought you might want to know.

```
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br>
<br>
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br>
<br>
<b>Fatal error</b>:  Uncaught exception 'Genghis_ErrorException' with message 'PHP warning:  Cannot modify header information - headers already sent' in ...
```

**Comment by bobthecow** [comment]
Hi! That warning has been fixed in the dev version of Genghis. It's here if you want to run it:

https://github.com/bobthecow/genghis/tree/develop

Otherwise, ignore the warning or set that flag in php.ini for now :)

**Comment by piengeng** [comment]
It's working on the develop tree, will use this tree from now on. thanks for this app btw.

**Comment by bobthecow** [comment]
No problem :)
