### ISSUE TITLE
Upgrade to latest Backbone version

### ISSUE THREAD

**Issue by julien-c** [bobthecow/genghis#21]
I'm currently in the process of learning Backbone. I noticed that Genghis uses a slightly old version of Backbone. Would you say it is still a good app I could learn Backbone from? Are you considering upgrading Backbone to a newer version?

**Comment by bobthecow** [comment]
I tried Genghis with the current versions of Backbone, Underscore and jQuery version on the dev branch, and everything works just fine. I'll bump the versions in the next release.

**Comment by bobthecow** [comment]
All vendor libraries are updated to their most current version in the `develop` branch, and going into the next (imminent) release.

**Comment by julien-c** [comment]
Great, thanks!

**Comment by bobthecow** [comment]
In case you missed it, v2.0 was released with current versions of all vendor libraries. Let me know if you have any questions.

**Comment by julien-c** [comment]
Wow, only just checked out v2.0, it is great! Super job!

**Comment by bobthecow** [comment]
Thank you :)
