### ISSUE TITLE
How to create an index?

### ISSUE THREAD

**Issue by georgeu2000** [bobthecow/genghis#219]
How to create an index?

**Comment by sagargulati** [comment]
Try creating the index with PHP command, genghis doesn't have one supported inbuild for now.

**Comment by georgeu2000** [comment]
OK, shall I add a note in the readme? Other people may wonder about this too.

**Comment by sagargulati** [comment]
Go ahead!

**Comment by georgeu2000** [comment]
https://github.com/bobthecow/genghis/pull/221
