### ISSUE TITLE
Dropdown List for collections needs to be wider or truncate

### ISSUE THREAD

**Issue by drudge** [bobthecow/genghis#22]
See: ![Screenshot](http://f.cl.ly/items/3L3P3P0Q3X1k1C1f1103/Screen%20Shot%202012-08-20%20at%202.27.09%20PM.png)

**Comment by bobthecow** [comment]
From your screenshot (and from how it works on my screen) it appears to be working as intended. What do you expect it to do instead?

**Comment by bobthecow** [comment]
Re-opening because I just found a case where it didn't work as intended. Fix coming right up :)
