### ISSUE TITLE
Include JSON Validator

### ISSUE THREAD

**Issue by patrickgalbraith** [bobthecow/genghis#23]
At the moment it is difficult to debug errors when adding a new document it would be awesome to have a button labeled "Validate" that would check the JSON for errors.

Have you thought about including something like this https://github.com/zaach/jsonlint/tree/master/web javascript based JSON validator.

They also have an online demo http://zaach.github.com/jsonlint/ as you can see the error output contains a detailed error message (line number etc).

**Comment by bobthecow** [comment]
A very good idea. I expect to add document validation to v2.0 — that'll be the next version released, barring any bug fixes in v1.4.x.

**Comment by patrickgalbraith** [comment]
@bobthecow awesome! I'm looking forward to it. If you need help testing let me know.

**Comment by bobthecow** [comment]
Will do.

**Comment by bobthecow** [comment]
Just a little teaser:

![](http://i.imgur.com/eOgP1.png)

**Comment by patrickgalbraith** [comment]
Wow!! That looks amazing, you definitely exceeded my expectations. Can't wait :D

**Comment by bobthecow** [comment]
JSON validation implemented for Genghis v2.0. Closing this issue.
