### ISSUE TITLE
Assigning negative number to a property results in "Unexpected UnaryExpression"

### ISSUE THREAD

**Issue by colinmutter** [bobthecow/genghis#31]
Simply reproducible by assigning a negative number to any document property. 

``` javascript
{
    _id: ObjectId("505739a508e8efc6a0000001"),
    test : -1
}
```

**Comment by bobthecow** [comment]
Thanks for the report! This was just fixed, see #29

The fix will go out in `v2.0.2`, due out later this afternoon. If you need it faster, feel free to grab `genghis.rb` or `genghis.php` from the `develop` branch.

**Comment by bobthecow** [comment]
Just released v2.0.2. All your UnaryExpression woes are over! :)

**Comment by colinmutter** [comment]
Ouch, sorry for the dupe. Thanks!

**Comment by bobthecow** [comment]
No worries. It's good to be on top of a bug, for once :P
