### ISSUE TITLE
Non-SSL connection causing mixed-content warning

### ISSUE THREAD

**Issue by gavinhungry** [bobthecow/genghis#32]
When Genghis retrieves a font from **fonts.googleapis.com**, it does it over a connection not secure by SSL.  This causes a mixed-content / partial-encryption warning in browsers when Genghis is served from an SSL source.

**fonts.googleapis.com** allows `https://`, which eliminates the warning.

**Comment by bobthecow** [comment]
Thanks for reporting this. I'll get a fix into `v2.1`.
