### ISSUE TITLE
"Couldn't get a file descriptor referring to the console" when starting genghis on Ubuntu

### ISSUE THREAD

**Issue by matthurne** [bobthecow/genghis#34]
On Ubuntu, I see the following when starting up genghis:

```
user@host:~$ genghisapp 
[2012-09-26 16:08:58 -0400] Starting 'genghisapp'...
[2012-09-26 16:08:58 -0400] trying port 5678...
Couldn't get a file descriptor referring to the console
```

Some quick web searches leads me to believe that the command being used to attempt to launch my web browser with the URL of the newly started genghis isn't quite right for Ubuntu. This is further evidenced by the fact that the browser launch never happens.

**Comment by bobthecow** [comment]
That's exactly what it's trying to do. This would be an issue in [Vegas](https://github.com/quirkey/vegas), which is what Genghis uses to launch the server and web client. Do you mind opening an issue there?

**Comment by matthurne** [comment]
Done: quirkey/vegas#15

**Comment by bobthecow** [comment]
Thank you. Closing this issue for now. Feel free to reopen if Vegas is unable to resolve your problem.

**Comment by priyolahiri** [comment]
A simple fix is to add -L to the command line when starting genghisapp. The error goes away. But using genghis with supervisor does not work as it shows exited too quickly, but is actually running.
