### ISSUE TITLE
Weird object render

### ISSUE THREAD

**Issue by kdauzickas** [bobthecow/genghis#38]
Another minor glitch in js. Not sure what causes this but I think it's 2 consecutive fields with arrays.
Data:
`{ _id: ObjectId("5074285671d82f2f61000000"), foo: [ { data: "data" } ], bar: [] }`

Expected render:

``` javascript
{
    _id: ObjectId("5074285671d82f2f61000000"),
    foo: [
        {
            data: "data"
        }
    ],
    bar: []
}
```

Actual render:

``` javascript
{
        _id: ObjectId("5074285671d82f2f61000000"),
        foo: [
        {
            data: "data"
        }
    ],
        bar: []
}
```

**Comment by bobthecow** [comment]
yeah, that isn't right. i'll try to track it down.

**Comment by bobthecow** [comment]
Thanks for reporting this. It was actually a problem with rendering properties containing only an empty array (`bar: []`). It's been fixed in `develop` and will go out with the next release.
