### ISSUE TITLE
Not really an issue but ...

### ISSUE THREAD

**Issue by danielb2** [bobthecow/genghis#39]
This is the first mongo browser I've tried that I liked straight away. Nice work!!

Hopefully this random compliment filed as an issue won't bother you too much. It's meant to promote happiness and satisfaction.

**Comment by bobthecow** [comment]
Thank you. I really appreciate that :)

Now your homework, since you bumped my issue count for a non-issue: 
1. What one feature would make you _love_ Genghis rather than just liking it? Show your work.

**Comment by danielb2** [comment]
rofl!  Now I have to work too :)  

It wasn't just one thing.
1. Easy of getting it up and running. Just a freaking gem. Who can complain about that?
2. no configuration necessary! It just starts, and runs. Even opened a browser window for me.
3. navigation is intuitive. ( I experienced momentary confusion when I tried to select a db from the dropdown that results from hovering over the number of databases available )

**Comment by danielb2** [comment]
Oh, a suggestion.   On the page: http://genghisapp.com/

It says to install the gem, I had to browse a bit to figure out what to execute to get it to run. Maybe you can add that in the instruction. My shell didn't pick it up so tab completion for `ghen<tab>` didn't work. (I obviously spelled it wrong, but you get the point).

**Comment by bobthecow** [comment]
Okay, [I've updated the documentation](https://github.com/bobthecow/genghis#there-are-more-ways-to-run-genghis-than-you-can-shake-a-stick-at), and given that a more prominent place on genghisapp.com. Hopefully that'll be enough :)

**Comment by danielb2** [comment]
Thanks :)  And Genghis still rocks! Was using it again today

**Comment by bobthecow** [comment]
Glad to hear it, and thank you!
