### ISSUE TITLE
Assets break when genghis.php is in subdir

### ISSUE THREAD

**Issue by kriswallsmith** [bobthecow/genghis#4]
i.e. http://localhost/~kriswallsmith/genghis

**Comment by bobthecow** [comment]
Are you running Apache? If so, what version?

Assets are loading for me, both with and without the included `.htaccess` file. Can you access them via the ugly URL, i.e. `http://localhost/~kriswallsmith/genghis/genghis.php/assets/style.css`?

**Comment by kriswallsmith** [comment]
Setting `RewriteBase` did the trick.

**Comment by jturolla** [comment]
Ok, but what for nginx?  There's no RewriteBase config there :c

**Comment by bobthecow** [comment]
True. Let's solve this in #6
