### ISSUE TITLE
doen't work

### ISSUE THREAD

**Issue by romanesko** [bobthecow/genghis#43]
```
sudo gem install bson_ext
Building native extensions.  This could take a while...
Successfully installed bson_ext-1.7.0
1 gem installed
```

and still I have:

```
MongoDB driver C extension not found.
Install this extension for better performance: gem install bson_ext`
```

**Comment by bobthecow** [comment]
Can you give me more details about your system? OS and version, Ruby flavor and version, etc?

**Comment by romanesko** [comment]
OSX 10.8.2 
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

**Comment by bobthecow** [comment]
And these:

```
gem which genghis
gem which bson
which -a genghisapp
which -a ruby
which -a gem
```

**Comment by bobthecow** [comment]
I just did a fresh install on 10.8.2:

```
$ /usr/bin/ruby --version
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

$ /usr/bin/gem which genghis
/Library/Ruby/Gems/1.8/gems/genghisapp-2.1.1/./genghis.rb
```

... and everything is working fine.

My guess is that you have multiple copies of `gem`, or multiple copies of `ruby` or multiple configurations somehow, and not all your gems get installed to the same place.

**Comment by bobthecow** [comment]
Ooh, one more possibility. You might need to restart `genghisapp` if you installed `bson_ext` since starting the app.

```
genghisapp --kill
genghisapp
```

**Comment by romanesko** [comment]
O yes! Thank you )

**Comment by x1a0** [comment]
I think I am facing same problem here and restart genghis doesn't help. I am running a Debian server.

``` bash
$ gem which genghis
/var/lib/gems/1.8/gems/genghisapp-2.1.6/./genghis.rb

$ gem which bson
/var/lib/gems/1.8/gems/bson-1.8.2/lib/bson.rb

$ which -a genghisapp
/var/lib/gems/1.8/bin/genghisapp

$ which -a ruby
/usr/bin/ruby

$ which -a gem
/usr/bin/gem
```
