### ISSUE TITLE
Genghis stuck

### ISSUE THREAD

**Issue by romanesko** [bobthecow/genghis#46]
It got stuck (

https://www.evernote.com/shard/s16/sh/f350f0cd-50a8-40d8-8f5f-494176d4afba/9ffcd6cee578648535c7fc4841aa9aef

I've also tried to update thr version, but `gem install genghisapp` installs the old version
The version downloaded from the site falls with the following error:

```
/Users/macmini/Downloads/genghis-2.1.2/genghis.rb:13:in `require': no such file to load -- mongo (LoadError)
    from /Users/macmini/Downloads/genghis-2.1.2/genghis.rb:13
```

**Comment by bobthecow** [comment]
I'm not sure why it's stuck, but I'd guess it's trying to connect to a server that's timing out. Try clearing your cookies and seeing if it loads.

`gem install genghisapp` should be installing v2.1.2 (that's the version listed on rubygems.org)... I don't know what's happening there.

If you're running the downloaded version under Ruby 1.8.x, you might need rubygems for it to work. Try this:

```
ruby -rubygems genghis.rb
```

**Comment by romanesko** [comment]
It stucks here:

GET http://0.0.0.0:5678/servers 500 (Internal Server Error) 

{"status":500,"error":"Database command 'listDatabases' failed: (errmsg: 'need to login'; ok: '0.0')."}

**Comment by bobthecow** [comment]
Ahh. Your server requires authentication? There's an outstanding bug with that (#16) in some cases, I expect to have it fixed for the next point release.

Closing as a duplicate.
