### ISSUE TITLE
When I add more than one server, the oldest one is removed from the list.

### ISSUE THREAD

**Issue by rschwabco** [bobthecow/genghis#50]

**Comment by bobthecow** [comment]
If you add a server and refresh the page, is the server still in the list?

What flavor of Genghis are you running? Is it behind a webserver, or reverse proxy, or is running standalone?

**Comment by rschwabco** [comment]
I add the second -> refresh -> first one isn't there.

I'm running Version 2.1.2 on a local MAMP, as a php process.

**Comment by bobthecow** [comment]
if you add a third, does the second stay?

**Comment by rschwabco** [comment]
Nope.

**Comment by bobthecow** [comment]
Oh, boo. That's no fun.

**Comment by rschwabco** [comment]
Otherwise it's super awesome :-)

**Comment by bobthecow** [comment]
This has been fixed in `develop`. It'll go out in the next release.
