### ISSUE TITLE
Saving a document with a date field in it causes the date value to revert to epoch time

### ISSUE THREAD

**Issue by asabhaney** [bobthecow/genghis#52]
Hello, I'm also having a problem with dates. Whenever I try and save a document containing a date, the date seems to reset to what seems like UNIX epoch time:

```
ISODate("1969-12-31T17:00:00-07:00")
```

When saving the document, I see that the response contains an error:

```
Warning: MongoDate::__construct() expects parameter 1 to be long, string given in /[...]/genghis.php on line 18
```

I am using MAMP (PHP 5.3.6), Mongo 2.2.0, and the version of the PHP driver I'm using is 1.2.12.

**Comment by bobthecow** [comment]
Ooh. Sorry about that. I just fixed this regression, download v2.1.3 to get the fix.

Thank you for reporting this.

**Comment by asabhaney** [comment]
Awesome, dates work perfectly now. Thanks!

**Comment by bobthecow** [comment]
No problem.
