### ISSUE TITLE
Error when running on windows

### ISSUE THREAD

**Issue by Leonas** [bobthecow/genghis#54]
This gem install fine but when I run it, I get the following error:

$ genghisapp
c:/RailsInstaller/Ruby1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require': cannot load such file -
- win32/process (LoadError)
      from c:/RailsInstaller/Ruby1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
      from c:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/vegas-0.1.8/lib/vegas/runner.rb:8:in`top (required)
  '
      from c:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/genghisapp-2.1.3/bin/genghisapp:11:in `top (required)
  '
      from c:/RailsInstaller/Ruby1.9.3/bin/genghisapp:19:in 'load'
      from c:/RailsInstaller/Ruby1.9.3/bin/genghisapp:19:in 'main'

**Comment by bobthecow** [comment]
I have honestly never used Ruby on Windows :)

I'll try to help, but I'm traveling so I don't have a windows instance handy to test this on. Do you mind trying something for me? Edit `c:/RailsInstaller/Ruby1.9.3/bin/genghisapp` and change out the `require File.expand_path` line for this:

```
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'genghis'))
```

**Comment by Leonas** [comment]
Looks like your app won't work on windows because of a dependency. I looked further into this and the vegas gem doesn't work with windows. In one of vegas' source files it said to do 'gem install win32-process' but then the daemon wasn't working and found that they have given up on making it work with windows:

https://github.com/quirkey/vegas/issues/3

Maybe you can use a different gem for that job because genghis is awesome but I use windows as well. At least it works on my macbook.

**Comment by bobthecow** [comment]
From that issue, it looks like it's just daemonization that is broken on windows. If you run it in the foreground (`-F` flag) does it work?

Regardless, if that's the issue you're running into, it should still work mounted in rack. Try the rack instructions?

https://github.com/bobthecow/genghis#in-an-existing-rack-app

**Comment by Leonas** [comment]
Awesome, running genghisapp -F fixed everything! Thanks!

**Comment by bobthecow** [comment]
Thanks for your help tracking this down. As of the next release, `genghisapp` will always run in the foreground for Windows users (and a note to that effect has been added to the README).

**Comment by runxc1** [comment]
So just curious how does this tell that its running on Windows.  I am trying to get this up and running on windows 8 and am running into these errors even with the -F flag

**Comment by bobthecow** [comment]
It's [here](https://github.com/bobthecow/genghis/commit/f812365d837dbd9a2a66c2ec89289d593cbfe677) and [here](https://github.com/quirkey/vegas/blob/master/lib/vegas.rb#L11)... I don't have a windows box with Ruby to test on, so I was relying on the built-in check in Vegas.

If it's not working for you, do you mind opening `irb` and checking what `RUBY_PLATFORM` is set to?

**Comment by runxc1** [comment]
i386-mingw32 is what it is set to.  As a side note I was able to set it up as a Rack app.  I had never set up a Rack app so didn't know that it was that easy.  For those that read this later just drop the config.ru in a directory and run the command "rackup config.ru" from the directory and you are good to go.

**Comment by bobthecow** [comment]
Oh, there's also this one:

``` bash
ruby `gem which genghis`
```

:)

**Comment by bobthecow** [comment]
if it's `i386-mingw32`, then the detection is working properly. it must be something with Vegas in Windows 8 then :-/

**Comment by bobthecow** [comment]
wait. is that how you say "interpolate the output of this command" in windows? i don't remember.

**Comment by runxc1** [comment]
C:/Ruby193/lib/ruby/gems/1.9.1/gems/genghisapp-2.1.6/./genghis.rb
 is the output from 
ruby `gem which genghis`

**Comment by bobthecow** [comment]
On *nix shells the backticks make it interpolate the result of the "which" call, but I don't know how to do that on Windows. It's the same as running:

```
ruby C:/Ruby193/lib/ruby/gems/1.9.1/gems/genghisapp-2.1.6/./genghis.rb
```
