### ISSUE TITLE
Create an example nginx config

### ISSUE THREAD

**Issue by bobthecow** [bobthecow/genghis#6]
`.htaccess` doesn't do much good there :)

**Comment by bobthecow** [comment]
I don't currently use nginx, so I'm not completely clear on what this requires. From what I've seen on the interwebs, this should do the trick?

https://gist.github.com/ecc09ddd870343208cfa

(or at least it's a start)

**Comment by jturolla** [comment]
Well, too bad, it didn't work. 

The server now answers to /genghis.php/script.js, but it sends the genghis.php result data instead of the script. 

(please check your twitter DM for the link)

No log output seems usefull:

200.233.55.38 - - [17/Dec/2011:11:39:58 +0000] "GET /genghis.php/assets/style.css HTTP/1.1" 200 3628 "http://<domain>/genghis.php/script.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:8.0.1) Gecko/20100101 Firefox/8.0.1"
200.233.55.38 - - [17/Dec/2011:11:39:58 +0000] "GET /genghis.php/assets/script.js HTTP/1.1" 200 3628 "http://<domain>/genghis.php/script.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:8.0.1) Gecko/20100101 Firefox/8.0.1"

**Comment by jturolla** [comment]
Sorry for not looking for a fix (since I'm the only one that is using nginx), I'll try but I'm a little busy these days.

**Comment by ShonM** [comment]
nginx here as well. I'm about to poke around with this, will report back with my findings.

**Comment by ShonM** [comment]
I'm going to stick with my own rewritten version that separates the compiled js/css from the php.

**Comment by vslinko** [comment]
```
server {
    root /var/www/genghis;

    location / {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/genghis.php;
        fastcgi_param SCRIPT_NAME $document_root/genghis.php;
        fastcgi_param PATH_INFO $uri;
    }
}
```

**Comment by bobthecow** [comment]
Does this work?

```
server {
    root /var/www/genghis;

    location / {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/genghis.php;
        fastcgi_param SCRIPT_NAME /genghis.php;
        fastcgi_param PATH_INFO $uri;
    }
}
```

**Comment by vslinko** [comment]
Yes, using now.

**Comment by bobthecow** [comment]
Awesome.

There's still an issue with the "ugly url" version when using nginx (to see it, navigate directly to `/genghis.php`). I'm not sure what the best fix would be for this, other than redirecting away from `/genghis.php` to `/`. Any ideas?

**Comment by vslinko** [comment]
My configuration work fine without /genghis.php

**Comment by vslinko** [comment]
Moreover, it does not work with `/genghis.php`

**Comment by bobthecow** [comment]
Yep. My concern is if someone uses it _with_ `/genghis.php` ... The apache version handles this case by falling back to ugly URLs. I think for nginx the ideal solution would be to redirect to `/` if someone navigates directly to `/genghis.php`.

**Comment by vslinko** [comment]
Ow, misunderstand you.

Yes, only redirect.

**Comment by lunixbochs** [comment]
```
server {
    root /var/www/genghis;

    location / {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/genghis.php;
        fastcgi_param SCRIPT_NAME /genghis.php;
        fastcgi_param PATH_INFO $uri;

        rewrite /genghis.php / permanent;
    }
}
```

**Comment by bobthecow** [comment]
@vslinko Does @lunixbochs' config look right? If so, let's create a wiki page for nginx and add it there, with any caveats.

**Comment by vslinko** [comment]
Tested. Works fine.

**Comment by ro-ka** [comment]
Works fine here, too. No wiki available… You should enable it in the repo settings.

**Comment by bobthecow** [comment]
@ro-ka Wiki enabled :)

**Comment by ro-ka** [comment]
@bobthecow Thanks! Will add it later.

**Comment by bobthecow** [comment]
I added basic instructions here: https://github.com/bobthecow/genghis/wiki

Feel free to update, organize, whatever :)

**Comment by ro-ka** [comment]
Great! Nothing to add right now. :)

So, this ticket can be closed, right?

**Comment by bobthecow** [comment]
Yup. Closing.

**Comment by gavinhungry** [comment]
This is my solution for installing Genghis in a subdirectory with **nginx** using `fastcgi_split_path_info` (the above solution only works for the root of a server, and `genghis.php` seems to look for "/assets/" only at the start of **PATH_INFO/REQUEST_URI**).

Genghis is installed to `/mongo/genghis.php`

It's not perfect.  I didn't really want to have the path in there twice (once on the `location` line and again in the `fastcgi_split_path_info` regex), but I don't think it's possible to use variables in an nginx conf regex (I may be wrong).

Hope this helps somebody.

```
location ~ ^/(mongo)/ {
  fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
  include fastcgi_params;
  set $script 'genghis.php';

  fastcgi_split_path_info ^(/mongo)(/?.+)$;
  fastcgi_param SCRIPT_FILENAME $document_root/$1/$script;
  fastcgi_param SCRIPT_NAME /$1/$script;
  fastcgi_param PATH_INFO $fastcgi_path_info;
}
```

**Comment by bobthecow** [comment]
@gavinhungry (and any other nginx users) — feel free to add create and link to an "nginx configuration" wiki page with examples other than the basic one on the wiki home page.

**Comment by nodesocket** [comment]
@gavinhungry,

Trying to setup Genghis in `PHP` with `Nginx` in a subdirectory `mydomain.com/mongodb`, and I have the following nginx config:

```
fastcgi_param SCRIPT_FILENAME $document_root/mongodb/genghis.php;
fastcgi_param SCRIPT_NAME /mongodb/genghis.php;
fastcgi_param PATH_INFO $fastcgi_path_info;
```

When I load `mydomain.com/mongodb/genghis.php` I am seeing the following in Chrome developers tools, and an incomplete page loading:

```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://mydomain.com/mongodb/genghis.php/assets/style.css?v=2.1.6". genghis.php:1
Resource interpreted as Script but transferred with MIME type text/html: "http://mydomain.com/mongodb/genghis.php/assets/script.js?v=2.1.6". genghis.php:1
Uncaught SyntaxError: Unexpected token < genghis.php/assets/script.js?v=2.1.6:1
Uncaught ReferenceError: jQuery is not defined
```

**Comment by gavinhungry** [comment]
@nodesocket,

Try adding this above your `fastcgi_param` lines:

```
fastcgi_split_path_info ^(/mongodb)(/?.+)$;
```

You want the CSS and JS resources served up as: `http://mydomain.com/mongodb/assets/style.css?v=2.1.6`
(note the absence of **genghis.php** here).

I was able to replicate your issue without `fastcgi_split_path_info`.

EDIT: more information available from http://wiki.nginx.org/HttpFastcgiModule#fastcgi_split_path_info

**Comment by nodesocket** [comment]
@gavinhungry,

Same issue. Here is my nginx config block:

```
fastcgi_pass 127.0.0.1:3000;
include /etc/nginx/fastcgi_params;

fastcgi_split_path_info ^/(mongodb)(/?.+)$;
fastcgi_param SCRIPT_FILENAME $document_root/mongodb/genghis.php;
fastcgi_param SCRIPT_NAME /mongodb/genghis.php;
fastcgi_param PATH_INFO $fastcgi_path_info;
```

**Comment by nodesocket** [comment]
@gavinhungry,

Never-mind, fixed. I was calling `http://mydomain.com/mongodb/genghis.php` when all I need is `http://mydomain.com/mongodb`.

Thanks for the help.

**Comment by bobthecow** [comment]
That's what I was talking about earlier... With Apache, it works both ways. With nginx, it's just awkward and broken. Mebbe the recommended config should hardcode a redirect away from `genghis.php`?
