### ISSUE TITLE
Add support to explain a query

### ISSUE THREAD

**Issue by mweibel** [bobthecow/genghis#60]
Hi,

thanks again for making genghisapp - I think it's the only useful mongodb inspector at the moment.

I've got a feature request: When you're doing a search using the input field at the top, it would be nice to have something like a checkbox or something like that which is doing an explain of the query you're trying to run.
Also if the result would be displayed nicely would be very nice :)

Thanks
Michael

**Comment by nicktacular** [comment]
+1 vote from me, this would be very nice

**Comment by x1a0** [comment]
+1, would be really helpful

**Comment by bobthecow** [comment]
Thanks to @craigerm, this has been implemented and is merged into `develop`. It'll be in the v2.4.0 release :)

**Comment by craigerm** [comment]
Awesome, thanks - Glad I could help! :D
