### ISSUE TITLE
Oversized greeting

### ISSUE THREAD

**Issue by kdauzickas** [bobthecow/genghis#61]
A suggestion: maybe the "Welcome to Genghis" message could be scaled down? On a 1366*768 monitor I see only one db entry. It's rather annoying that I need to scroll every single time.
There's a reason why main content is usually placed near the middle of the page!

**Comment by bobthecow** [comment]
Ahh, but your mistake is in assuming that the oversized "Welcome to Genghis" message _isn't_ the main content ;)

**Comment by bobthecow** [comment]
This has been fixed in `develop`. I've made the header vertically responsive as well as horizontally responsive, so wide-and-shortish windows will be able to see more of the server list. The change will go out in the next release.
