### ISSUE TITLE
Can't create a document with the _id field already set

### ISSUE THREAD

**Issue by asabhaney** [bobthecow/genghis#64]
When adding a new document to a collection, I am not able to have the _id field already filled in (I have ensured it is unique within the collection).

When attempting to do so, the following AJAX response is something like this: 

```
{"error":"Document '506aca5e2cc4098b0f00002c' not found in 'tests'","status":404}
```

And the modal window does not close.

In addition, when editing a document, if I attempt to change the value of _id, the _id change is reflected when hitting the 'Save' button - this should probably show an error instead. Of course, this save is not reflected when refreshing the page and looking at the document again.

I am running the current version of Genghis (2.1.6) on MAMP (PHP 5.3.6), using MongoDB v2.2.0, PHP driver  v1.2.12.

Thanks for the great app!

**Comment by bobthecow** [comment]
Thanks for reporting this. I just pushed a fix for the second issue (it's in `develop` and will be released in `2.1.7`). I'm working on a fix for the first issue.

**Comment by bobthecow** [comment]
And the other half is fixed as well. If you want to try it out, grab `genghis.php` from the develop branch.

Thanks again!

**Comment by asabhaney** [comment]
No problem! Just gave it a quick test run, works as expected now.

Thanks for the quick reply and fix.
