### ISSUE TITLE
New documents with _id

### ISSUE THREAD

**Issue by kdauzickas** [bobthecow/genghis#65]
When inserting new documents with id's, e.g. `{_id:"derp"}` genghis fires a PUT (instead of a POST) resulting in a failed update

**Comment by bobthecow** [comment]
Yup. It's fixed in develop (see #64 and 6ed8804174c57d771a02cf4cb7b67e5fedf22de0).

The fix will go out with v2.2. If you just can't wait, feel free to run the develop branch.
