### ISSUE TITLE
mongo installed on different port

### ISSUE THREAD

**Issue by panosru** [bobthecow/genghis#66]
Hello, what if mongo is not set on default port 27017 ?

Also when I try to install mongodb driver c extension I'm getting the following:

```
root@dev:~# gem install bson_ext
Fetching: i18n-0.6.1.gem (100%)
Fetching: multi_json-1.4.0.gem (100%)
Fetching: activesupport-3.2.9.gem (100%)
Fetching: bson-1.8.0.gem (100%)
Fetching: bson_ext-1.8.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed i18n-0.6.1
Successfully installed multi_json-1.4.0
Successfully installed activesupport-3.2.9
Successfully installed bson-1.8.0
Successfully installed bson_ext-1.8.0
5 gems installed
Installing ri documentation for i18n-0.6.1...
Installing ri documentation for multi_json-1.4.0...
Installing ri documentation for activesupport-3.2.9...

unrecognized option `--encoding'

For help on options, try 'rdoc --help'

ERROR:  While generating documentation for activesupport-3.2.9
... MESSAGE:   exit
... RDOC args: --ri --op /usr/lib/ruby/gems/1.8/doc/activesupport-3.2.9/ri --encoding UTF-8 lib --title activesupport-3.2.9 Documentation --quiet
```

Thanks

**Comment by panosru** [comment]
Ok, just figured out that I can use localhost:12345

**Comment by bobthecow** [comment]
That's how you do it.

I don't know anything about what's going on with your gem situation. My guess would be that you've got something weird in your `.gemrc` or with the currently installed versions of something... Try `gem install bson_ext --no-rdoc`

**Comment by panosru** [comment]
@bobthecow thank you for your reply! I tried it, although it says that it is installed successfully I'm still getting that message:

```
root@dev:/# gem install bson_ext -no-rdoc
Building native extensions.  This could take a while...
Successfully installed bson_ext-1.8.0
1 gem installed
Installing ri documentation for bson_ext-1.8.0...
Installing RDoc documentation for bson_ext-1.8.0...
root@dev:/# genghisapp

**Notice: C extension not loaded. This is required for optimum MongoDB Ruby driver performance.
  You can install the extension as follows:
  gem install bson_ext

  If you continue to receive this message after installing, make sure that the
  bson_ext gem is in your load path and that the bson_ext and mongo gems are of the same version.

[Thu Dec 06 19:14:35 +0200 2012] Starting 'genghisapp'...
[Thu Dec 06 19:14:35 +0200 2012] trying port 5678...
```

**Comment by bobthecow** [comment]
Did you ensure that the bson_ext and mongo gems are the same version?

If you run `irb` then enter:

```
require 'bson'
require 'bson_ext/cbson'
```

What does it say?

**Comment by panosru** [comment]
@bobthecow Not sure how to check if bson_ext and mongo gems are the same version...

Here is the output from what you asked

```
# irb
irb(main):001:0> require 'bson'
LoadError: no such file to load -- bson
    from (irb):1:in `require'
    from (irb):1
    from :0
irb(main):002:0> require 'bson_ext/cbson'
LoadError: no such file to load -- bson_ext/cbson
    from (irb):2:in `require'
    from (irb):2
    from :0
irb(main):003:0> 
```

**Comment by bobthecow** [comment]
Try the same but with `bundle exec irb` instead?

**Comment by panosru** [comment]
@bobthecow Hello, just tried it:

```
# bundle exec irb
Could not locate Gemfile
```

Thanks in advance!

**Comment by bobthecow** [comment]
If you're not using a Gemfile it couldn't be bundler giving you incorrect versions. Something is wonky with your setup. I'd bet that you have multiple versions of `gem`, `ruby` and/or `irb` installed.

Are you using rbenv, RVM, or another ruby version manager?

**Comment by godbout** [comment]
I kept having the same issue. Using RVM, Ruby version 1.9.3-p327. I don't think it's a environment problem.

I've realized that I had several version of mongo and bson installed, both of the gems had 1.7.1 and 1.8.0. bson_ext had only 1.8.0. So to be sure that all the gems had the same versions, I've uninstalled the 1.7.1s, and genghisapp. When I've reinstalled genghisapp, it forced back the installation of the 1.7.1 gems. So I've concluded that bson_ext had to be 1.7.1 also. Forced the version with:
`gem install bson_ext -v 1.7.1`
It works now.

Maybe a little update is needed somewhere. Or require the last version of the gems (1.8.0), or update the help message to precise the installation of the 1.7.1 version.

**Comment by panosru** [comment]
@bobthecow Hi, yes I use RVM

```
root@dev:/# rvm list

rvm rubies

 * ruby-1.9.2-p318 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

```
root@dev:/# gem -v
1.8.19
```

as @godbout said I also have 1.8.0 and 1.7.1

```
root@dev:/# gem list | grep bson_ext
bson_ext (1.8.0, 1.7.1)
```

So I removed `bson_ext` both versions and also `genghisapp`

```
root@dev:/# gem uninstall genghisapp
Remove executables:
    genghisapp

in addition to the gem? [Yn]  Y
Removing genghisapp
Successfully uninstalled genghisapp-2.1.6
root@dev:/# gem uninstall bson_ext

Select gem to uninstall:
 1. bson_ext-1.7.1
 2. bson_ext-1.8.0
 3. All versions
> 3
Successfully uninstalled bson_ext-1.7.1
Successfully uninstalled bson_ext-1.8.0
```

Then I force install `bson_ext` v1.7.1 as @godbout  proposed and after that install `genghisapp`

```
root@dev:/# gem install bson_ext -v 1.7.1
Fetching: bson_ext-1.7.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed bson_ext-1.7.1
1 gem installed
Installing ri documentation for bson_ext-1.7.1...

No definition for method_serialize

No definition for method_deserialize

No definition for method_max_bson_size

No definition for method_update_max_bson_size
Installing RDoc documentation for bson_ext-1.7.1...

No definition for method_serialize

No definition for method_deserialize

No definition for method_max_bson_size

No definition for method_update_max_bson_size
root@dev:/# gem install genghisapp
Fetching: genghisapp-2.1.6.gem (100%)
Successfully installed genghisapp-2.1.6
1 gem installed
Installing ri documentation for genghisapp-2.1.6...
Installing RDoc documentation for genghisapp-2.1.6...
root@dev:/# gem list | grep bson_ext
bson_ext (1.7.1)
```

Now when I try to run `genghisapp` I get this:

```
root@dev:/# genghisapp
[Thu Dec 13 14:53:29 +0200 2012] Starting 'genghisapp'...
[Thu Dec 13 14:53:29 +0200 2012] trying port 5678...
```

Problem solved :D seems that I had to re-install `genghisapp` after `bson_ext` installation :)

Thanks!

**Comment by bobthecow** [comment]
@godbout Ooh. That would do it. I forgot `genghisapp` gem optimistically depended on `mongo` gem version `1.7.0`. I'll update the alert to specify a version, since the `bson_ext` and `mongo` gem versions need to match.

I'll update it to require (allow?) the latest version of the gem as well, at some point, but even then it will need better messaging whenever v `1.9.0` is released.

**Comment by panosru** [comment]
@bobthecow :+1:

**Comment by bobthecow** [comment]
Additionally, if you install `bson_ext` while you're running Genghis daemonized, you have to kill it and restart before it starts working. We're already detecting this when a new version of Genghis is installed, but I'm adding a similar "restart required" message for bson_ext.

**Comment by panosru** [comment]
;) good to know! Thanks!

**Comment by bobthecow** [comment]
(For anyone stumbling upon this issue in the future, it's not necessary to reinstall the `genghisapp` gem after installing `bson_ext`, all you need to do is `genghisapp --kill; genghisapp` to restart it.)
