### ISSUE TITLE
Any chance to make genghisapp work with port forwarding?

### ISSUE THREAD

**Issue by godbout** [bobthecow/genghis#68]
Maybe I've misunderstood something.

The data I want to check is running on a vagrant VM. I can connect mongo from the host by specifying the port (27018 on the host is forwarded to 27017 on the VM) but I can't make genghis connect to it. Is there a way? I can access with other tools but genghis looks too awesome.

Thanks.

**Comment by godbout** [comment]
Typical behavior: I look for an hour, I post, then I discover that I mixed the server page with the db page. So if someone else is looking for the answer (hope... haha), well, just register the server in the first genghis page.

**Comment by bobthecow** [comment]
Heh. It does tend to work better when you add servers on the servers page :)

**Comment by ghost** [comment]
@godbout hey, my port-forwarded mongo db url is 127.0.0.1:27018 so i run `genghisapp  -s admin:<password>@127.0.0.1:27018/admin --port  2000` but can't connect. Everything is fine when i use mongo client command. What could be wrong?

**Comment by bobthecow** [comment]
@kelonye Have you tried entering that URL directly on the Genghis "Servers" page?

**Comment by ghost** [comment]
@bobthecow yeah, added `admin:<password>@127.0.0.1:27018/admin` and got ![screenshot.com](http://goo.gl/ud8xuu)

**Comment by bobthecow** [comment]
Do you have a read slave on that port?

**Comment by ghost** [comment]
Not sure about that, but `mongo --host 127.0.0.1 --port 27018 -u admin -p <password> admin` works fine.

**Comment by bobthecow** [comment]
Maybe it's a problem with the ruby driver? Try this:

```
$ irb
irb> require 'mongo'
irb> c = Mongo::MongoClient.from_uri 'mongodb://admin:<password>@127.0.0.1:27018/admin'
irb> c.database_names
```

**Comment by ghost** [comment]
Getting

``` ruby
=> ["component", "admin", "local", "test"]
irb#1(main):011:0> 
```

**Comment by bobthecow** [comment]
That's strange, because that's just how Genghis is connecting. 

Are you using rbenv or RVM or something else that might be monkeying with gem versions or ruby paths?

**Comment by bobthecow** [comment]
Ooh! Does your password have any characters which would need to be escaped in a URL?

**Comment by ghost** [comment]
here's the password `RYkku6bFix4q`. So I had this problem last week when i was using rvm and now using system wide ruby.
