### ISSUE TITLE
Query error message, nice to have

### ISSUE THREAD

**Issue by nicktacular** [bobthecow/genghis#72]
If you make a mistake in your query that's still valid JSON but it's not valid Mongo query syntax, it would be nice to get an error instead of thinking you're waiting a long time for data. For example, the following is invalid but a tired coder may not notice:

```
{Status:{$neq:"Published"}}
```

It would be nice to send back a message saying it's invalid syntax.

(What I really meant was `{Status:{$ne:"Published"}}`).

**Comment by bobthecow** [comment]
Agreed. In fact, it is giving you a useful message, you just can't see it :)

``` json
{"error":"exception: invalid operator: $neq","status":400}
```

**Comment by nicktacular** [comment]
Cool! I'll run it with Firebug moving forward :)

**Comment by bobthecow** [comment]
No, I'll fix it. I just haven't gotten around to handling all of these cases yet :P

**Comment by bobthecow** [comment]
This has been fixed in `develop`, and it'll go out in the next release. Thanks for reporting it :)

**Comment by nicktacular** [comment]
Thank you!

**Comment by bobthecow** [comment]
No problem.
