### ISSUE TITLE
Can't connect to auth-enabled server

### ISSUE THREAD

**Issue by dantetwc** [bobthecow/genghis#73]
Hi,
I tried to connect my MongoDB which is auth-enabled

```
login:password@mongodb.example.com
```

It keeps saying malformed URI, how can I solve it?

**Comment by bobthecow** [comment]
That should work. What Genghis version are you running? And which backend?

**Comment by dantetwc** [comment]
I am using rubygem version 2.1.6

**Comment by bobthecow** [comment]
Oh, I got it. You need to authenticate against a DB. If your user has global privileges, just authenticate against admin:

```
login:password@mongodb.example.com/admin
```

I'll make this a better experience in v2.2.0.

**Comment by bobthecow** [comment]
Note that this is only a problem with the Ruby backend. Apparently the PHP MongoDB driver implicitly authenticates against `admin` if no database is specified, but the Ruby driver throws an exception. I'll make the Ruby backend act like the PHP driver.

**Comment by dantetwc** [comment]
Thanks 

```
login:password@mongodb.example.com/admin
```

it works now
