### ISSUE TITLE
Can't delete document

### ISSUE THREAD

**Issue by danpolites** [bobthecow/genghis#78]
I updated to 2.2.0 and I am unable to delete documents. The document _ids are typed as a String and not ObjectID. When I try to delete a document, I receive this error:

757: unexpected token at '"51130f5f30049a4c54ba2dc7"'

I'm using Mongo 2.2.3

**Comment by bobthecow** [comment]
Thanks for reporting this.

Which Genghis backend are you using? Which Mongo driver version do you have installed? Can you give me an empty document (i.e. one with just an `_id`) that causes this issue?

**Comment by danpolites** [comment]
I've installed genghis using gem install genghisapp, I'm using ruby 1.9.3p374 (2013-01-15 revision 38858) [x86_64-darwin12.2.1] along with the bson (1.8.2, 1.7.1), bson_ext (1.8.2) gems. If I browse to my collection and click Add Document and input the document below, I receive the same error, but it does insert. Attempting to delete results in the above error.

{
    _id: "test"
}

**Comment by bobthecow** [comment]
Yep. This is definitely an issue with the Ruby backend. The same document works in PHP just fine. I'll dig in a bit and see if I can figure out what's up.

**Comment by bobthecow** [comment]
There we go. It's fixed in the `develop` branch if you want to try it out, or you can wait for v2.2.1. I'm thinking that will go out Monday or Tuesday.

**Comment by danpolites** [comment]
I had a chance to try out the develop branch and it works good on my end. Thanks for having a look at it.

**Comment by bobthecow** [comment]
Great, thanks!
