### ISSUE TITLE
Change the document creation hotkey to something else

### ISSUE THREAD

**Issue by julien-c** [bobthecow/genghis#79]
The shortcut for document, collection or database creation (`c`) conflicts with the OS's `copy` (which is very natural to use in Genghis too). Could we find another shortcut that would not conflict with anything major?

That would be great!

**Comment by bobthecow** [comment]
But it shouldn't be conflicting with `cmd+c` or `ctrl+c`... Are you seeing otherwise?

**Comment by julien-c** [comment]
Yup, it conflicts with `cmd+c` on my Mac at least. Which modifier key is it supposed to hook into?

**Comment by bobthecow** [comment]
Just `c` (no modifier). What browser (and version) and OS version are you using?

**Comment by julien-c** [comment]
Latest Chrome (it's been doing that ever since I started using Genghis, that's why I was thinking it was intentional), OS X Lion.

You know what, it might be because of the way I press `cmd+c` (I might press both then release `cmd` a few ms before `c`...). So it's probably a bug with my typing. Sorry for the false alert.

**Comment by bobthecow** [comment]
Does pressing `cmd+c` that way reliably copy elsewhere? It's possible that I could swap out my hotkeys library for one that handles keydown/keyup for modifier keys. Right now I think it's just "modifier is pressed when key is released", but if that's not how hotkeys work system wide, I'm open to finding a new hotkeys library :)

**Comment by bobthecow** [comment]
If I understand correctly, you're doing:

```
KeyDown Cmd
KeyDown c
KeyUp   Cmd
KeyUp   c
```

and I'm doing:

```
KeyDown Cmd
KeyDown c
KeyUp   c
KeyUp   Cmd
```

Is that right?

**Comment by julien-c** [comment]
I'd need a slo-mo camera to figure out what exactly I am doing, but yes, you're right. 

Yes, I've never had a reliability issue with my copy-pasting :) Does your first schema not work on your setup (to copy)?

I just spent a few minutes trying to reprogram my brain to do it _your_ (probably the more frequent) way but I'm having a pretty hard time.

I can investigate hotkeys library if you'd like.

**Comment by bobthecow** [comment]
Hokay. Hotkey handling is improved across the board in b66e426 ... I've tested it with your weird sequence, and it seems to perform as expected :)

That's available in the `dev` branch. Mind checking it out and making sure it works for you?

**Comment by julien-c** [comment]
It does work flawlessly. Justin, you're a personal hero of mine :)

:beers:

**Comment by bobthecow** [comment]
Sweet!

The new version should be released today. I'm just tidying up a few loose ends.

**Comment by bobthecow** [comment]
And done :)
