### ISSUE TITLE
MongoId's aren't printed if PECL driver < 1.0.11

### ISSUE THREAD

**Issue by jmikola** [bobthecow/genghis#8]
I was using Genghis with an outdated PECL driver and noticed that MongoId's were no being rendered in the app. They'd show up as `{}` or `[Object object]` in document headers.

You'll need to handle these specially (probably with a string cast) in versions before 1.0.11:

> Added $id field to MongoId so that json_encode turns it into {$id:...}

http://pecl.php.net/package-info.php?package=mongo&version=1.0.11

**Comment by bobthecow** [comment]
The fix has been released in v1.2.0. Thanks for reporting!
