### ISSUE TITLE
Connecting to Heroku MongoDB instance hangs

### ISSUE THREAD

**Issue by jlyonsmith** [bobthecow/genghis#80]
If I add a server for a Heroku MongoDB instance I get "NaN" in the database size field, and when I click on the server it hangs and genghis is hung.  When I restart I get a weird message about some object not having a 'stats' method, and I have to delete the genghis cookie.  

I can give you more details if you would like, but I repro'd this with a free Heroku account and I figure you should be able to do the same and get more useful information.

**Comment by bobthecow** [comment]
Is it MongoLab or MongoHQ? Is this the same as #74?

**Comment by jlyonsmith** [comment]
Yep, that's it.

John.

On Feb 20, 2013, at 6:01 PM, Justin Hileman notifications@github.com
wrote:

Is it MongoLab or MongoHQ? Is this the same as
#74https://github.com/bobthecow/genghis/issues/74
?

—
Reply to this email directly or view it on
GitHubhttps://github.com/bobthecow/genghis/issues/80#issuecomment-13868633.

**Comment by bobthecow** [comment]
Great. I'll close this one in favor of #74. Which I'm still working on a fix for :)
