### ISSUE TITLE
sudo gem install genghisapp doesn´t work - (os x version 10.8.2)

### ISSUE THREAD

**Issue by MartinKolb1987** [bobthecow/genghis#82]
hi, 
i´ve just tried to install genghisapp. 
The console throws always an exception.
(some people wrote i have to install xcode... it doesn´t work). 
Have someone an idea for that problem?

```
Building native extensions.  This could take a while...
ERROR:  Error installing genghisapp:
    ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/ruby.h


Gem files will remain installed in /Library/Ruby/Gems/1.8/gems/eventmachine-1.0.0 for inspection.
Results logged to /Library/Ruby/Gems/1.8/gems/eventmachine-1.0.0/ext/gem_make.out
```

Thanx. Cheers, Martin

**Comment by bobthecow** [comment]
If you've installed Xcode and are still getting this error, you are most likely missing the "Command Line Tools", which includes things like compilers.

In the latest version of Xcode, you install these in Preferences > Downloads > Components

**Comment by MartinKolb1987** [comment]
thanx a lot, it works like a charm!

**Comment by bobthecow** [comment]
Great. Happy to help.

**Comment by joshuataylor** [comment]
Those googling who are using Ubuntu, use the following command to run "genghisapp":

sudo apt-get install ruby1.9.1-dev

Then rerun
sudo gem install genghisapp

**Comment by simondelliott** [comment]
Im using Mavericks and have installed command line tools, but this issue is still happening. 
Wondering if there are any ideas on what to try next.

**Comment by bobthecow** [comment]
@simondelliott Are you running into the exact same error?

**Comment by simondelliott** [comment]
The error is identical, tried lots and lots of things. 
in the end I just ran genghis using the ruby genghis.rb command. I have a feeling that the command line tools in the latest version of xcode are a bit screwy
