### ISSUE TITLE
Very slow when no network connection

### ISSUE THREAD

**Issue by lawrien** [bobthecow/genghis#83]
I lost my internet connection yesterday whilst using Genghis. Not a problem as I was accessing a local mongo instance. However, it seemed that every operation took an age, almost like it was constantly trying to connect to the internet every time I did something, and then having to wait for a timeout until it completed it's operation. 

Genghisapp 2.2.1, Mac OS X Lion, Ruby 1.9.3 (p385 I think).

Note that I did have remote servers configured in the servers page, although I wasn't (obviously) interacting with them.

**Comment by bobthecow** [comment]
Hrm. A truly unreachable server should time out fairly fast. And that wouldn't affect every action, just things involving refreshing the server list.

I'm unable to reproduce this by simply disabling my internet connection. It still works for localhost, and in fact, is faster than when it can connect to the remote servers I have listed :)

I'll play around with Charles and simulate latency and intermittent connection issues when I get a minute and see if I can reproduce this. In the meantime, next time that happens do you mind opening WebKit inspector and checking the network tab to see what it's hanging on?

**Comment by lawrien** [comment]
Hm indeed, now I can't reproduce either :-( At the time, I was sure that Genghis was upto something, but now I'm not so sure that it wasn't either the browser, mongo or even something else causing the problem. I guess I was probably a little to premature in raising this as an issue, so I'll close it now. If I ever encounter the same issue again, I'll try and do a little PD first and be sure to let you guys know if it's anything to do with Genghis. Apologies for wasted bandwidth.

**Comment by bobthecow** [comment]
No worries. I'd rather hear about issues than not. Let me know if you run into this again!
