### ISSUE TITLE
Getting "undefined method" error on first load

### ISSUE THREAD

**Issue by davidhlee** [bobthecow/genghis#84]
I'm getting this error when ghenghis first boots up in my browser:
undefined method `stats' for ["DATABASE_NAME"]:Array.

Similarly, how do you connect to a remote database: mongodb://USER:PASSWORD@SERVER:PORT/SERVICE_NAME

**Comment by bobthecow** [comment]
I imagine this is related to #69 and #74... Sometimes non-admin mongo users cause Genghis problems.

**Comment by bobthecow** [comment]
Check the just-released `v2.3.0`… It should fix all problems when authenticating against a single db.
