### ISSUE TITLE
Cannot run app, error `binread': undefined method `convert_to_path' for Backports:Module (NoMethodError)

### ISSUE THREAD

**Issue by denisvolokh** [bobthecow/genghis#85]
$ genghisapp
/Library/Ruby/Gems/1.8/gems/backports-3.1.0/lib/backports/1.9.1/io/binread.rb:6:in `binread': undefined method`convert_to_path' for Backports:Module (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/sinatra-1.3.5/lib/sinatra/base.rb:1127:in `inline_templates='
    from /Library/Ruby/Gems/1.8/gems/sinatra-1.3.5/lib/sinatra/base.rb:1061:in`**send**'
    from /Library/Ruby/Gems/1.8/gems/sinatra-1.3.5/lib/sinatra/base.rb:1061:in `set'
    from /Library/Ruby/Gems/1.8/gems/sinatra-1.3.5/lib/sinatra/base.rb:1087:in`enable'
    from /Library/Ruby/Gems/1.8/gems/sinatra-1.3.5/lib/sinatra/base.rb:1087:in `each'
    from /Library/Ruby/Gems/1.8/gems/sinatra-1.3.5/lib/sinatra/base.rb:1087:in`enable'
    from /Library/Ruby/Gems/1.8/gems/genghisapp-2.2.2/genghis.rb:824
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Library/Ruby/Gems/1.8/gems/genghisapp-2.2.2/bin/genghisapp:9
    from /usr/bin/genghisapp:23:in `load'
    from /usr/bin/genghisapp:23

Could you help me to resolve this?

Also while installing I had following error 
14 gems installed
Installing ri documentation for rack-1.5.2...
Installing ri documentation for vegas-0.1.11...
Installing ri documentation for rack-protection-1.4.0...
Installing ri documentation for tilt-1.3.4...
Installing ri documentation for sinatra-1.3.5...

unrecognized option `--encoding=UTF-8'

For help on options, try 'rdoc --help'

ERROR:  While generating documentation for sinatra-1.3.5
... MESSAGE:   exit
... RDOC args: --ri --op /Library/Ruby/Gems/1.8/doc/sinatra-1.3.5/ri --line-numbers --inline-source --title Sinatra --main README.rdoc --encoding=UTF-8 lib README.de.rdoc README.es.rdoc README.fr.rdoc README.hu.rdoc README.jp.rdoc README.ko.rdoc README.pt-br.rdoc README.pt-pt.rdoc README.rdoc README.ru.rdoc README.zh.rdoc LICENSE --title sinatra-1.3.5 Documentation --quiet

**Comment by bobthecow** [comment]
Hmm. I have no idea what this is about.

I take it you're installing on OS X, using the system installed Ruby instance, and it's 1.8.x? What is the actual Ruby version? What is your RubyGems version?

Are you using anything like rvm or rbenv?

**Comment by denisvolokh** [comment]
ruby 1.8.7
gem 1.8.24

I dont use rvm

**Comment by dustinrb** [comment]
I was able to run the app after installing backports 3.0.0 (the current version as of March 5, 2013 is 3.1). You may may have to uninstall 3.1.
Run:
$ gem uninstall backports
$ gem install backports -v 3.0.0

**Comment by bobthecow** [comment]
I filed a bug report with Backports: marcandre/backports#71

I'm closing this issue, since it's clearly a bug with that library. Thanks for helping track it down, @dustinrb :)

**Comment by marcandre** [comment]
My apologies for the trouble. It's fixed in backports 3.1.1

**Comment by bobthecow** [comment]
No worries. Thanks for the quick response!
