### ISSUE TITLE
Running "rake build:js" task fails 

### ISSUE THREAD

**Issue by craigerm** [bobthecow/genghis#86]
Hey there,

I was trying to build this locally but running `rake build:js` results in the following error:

```
Don't know how to build task 'vendor/jquery.hoverintent.js'
```

This is because the file on task is named `jquery.hoverIntent.js` but in the rakefile the file lists has it as `jquery.hoverintent.js` (Note the casing difference).

I'm not sure if anyone else is having this problem. I'm running ruby 1.9.3 on Ubnuntu 12.10 so maybe it's related to that. I tried different versions of rake too and they all have the same problem.

The fix is pretty simple - I'll send over the PR in a second.

Thanks - and I love this tool!

Craig

**Comment by bobthecow** [comment]
Oh, thanks for catching that. I'll get it merged.

It's not Rake related, it's case-sensitive filesystem related. Mine isn't, so it's hard to notice when something gets typod like that.

**Comment by craigerm** [comment]
Awesome thanks! I had a feeling it was related to that since I didn't see any one else with the problem.

**Comment by bobthecow** [comment]
This has been merged into `develop`, and will go into the next release. Thanks again.

**Comment by craigerm** [comment]
No worries - glad I could help! :smile:

**Comment by bobthecow** [comment]
Annnd released. Thanks again!
