### ISSUE TITLE
MongoDB::__construct(): invalid name $CLUSTER

### ISSUE THREAD

**Issue by kdauzickas** [bobthecow/genghis#89]
MongoClient::VERSION === 1.3.4
MongoDB Version: 2.4.1
Error started to appear after I updated the server to 2.4.0
It's triggered when trying to get databases from the server (genghis.php/servers/id%40password/databases).
Not sure if this issue is reproducible by others or is a consequence of (mis)configuration on server side.
`{"error":"MongoDB::__construct(): invalid name $CLUSTER","status":500}`

Note: I tried to investigate in more depth myself, but I wasn't able to build a develop version of genghis as rake aborts every time with `less.Parser` error

Edit2: actually the error was caused by a database named "$CLUSTER". Not sure how it got created as sharding isn't enabled on that particular server. Given that database naming restrictions do not allow $ character I guess genghis should ignore and not even list that database

**Comment by bobthecow** [comment]
So before you upgraded to 2.4, this same database worked in Genghis? Or didn't show up in the list? Or...

**Comment by bobthecow** [comment]
^ I just fixed a missing paren in LESS. Apparently an older version of the library was able to deal with it, but I updated to the latest and it started getting a `less.Parser` error for me as well. Thanks for reporting that.

**Comment by kdauzickas** [comment]
Either the database didn't exist before upgrade or was hidden from genghis/mongo shell/all other clients I tried. I tend to believe the latter as I couldn't find any references to this database except mongodb source.

**Comment by bobthecow** [comment]
Thanks for reporting this. It has been fixed in `v2.3.0`!
