### ISSUE TITLE
Malformed url's corrupt servers cookie

### ISSUE THREAD

**Issue by kdauzickas** [bobthecow/genghis#90]
Reproduce:
add server 'a:b'
(delete or leave the malformed server)
add server 'b:c'

Expected behavior:
I should be able to remove the entries

What happens:
Can't remove the second entry, the cookie gets corrupted and makes genghis unusable after a page refresh

**Comment by bobthecow** [comment]
Thanks for reporting this. I'll check it out.

Was this the Ruby or PHP backend?

**Comment by bobthecow** [comment]
This has been fixed in `v2.3.0`. Thanks for the bug report.
