### ISSUE TITLE
Authenticating against a single database

### ISSUE THREAD

**Issue by kdauzickas** [bobthecow/genghis#91]
Reproduce:
add server in form `username:password@domain.com/database`

Expected behavior:
after clicking on the server I see only the database the user was authenticated against or I get get to see the servers collections

What happens:
404 happens

**Comment by bobthecow** [comment]
Genghis doesn't (always?) support authenticating against a single database. See #69 and #74 ... It's my highest priority for the next release, so I hope to have a fix soon.

**Comment by bobthecow** [comment]
Check the just-released `v2.3.0`… It should fix all problems when authenticating against a single db.

**Comment by kdauzickas** [comment]
Sorry, no. The bug is still there. It's with the php backend.

**Comment by bobthecow** [comment]
Ahh. I bet you're using Apache?

See #62 and https://github.com/bobthecow/genghis/wiki#apache-configuration for a fix.

**Comment by kdauzickas** [comment]
Yup, this was it. Thanks

**Comment by bobthecow** [comment]
Awesome!

I'm looking for a better long-term solution, but in the interim I should prolly document that fix a bit more as well.
