### ISSUE TITLE
Update Queries

### ISSUE THREAD

**Issue by egyptianbman** [bobthecow/genghis#97]
First, wow... thanks for such an awesome app!

I'd love to be able to run update queries.  Editing 100s of entries one-by-one gets tedious.  ( If this already exists please let me know where.. All I saw was a search feature. )

Thank you!

**Comment by bobthecow** [comment]
Genghis doesn't currently do update queries. It's on the roadmap (somewhere), but I'd suggest running those via the mongo CLI shell for now.

**Comment by egyptianbman** [comment]
Sounds good, just wanted to make sure I wasn't overlooking the feature.  Keep up the good work, thanks!
