### ISSUE TITLE
Genghis installation issue

### ISSUE THREAD

**Issue by 0x80** [bobthecow/genghis#99]
Not really a Genghis issue but I don't know where to ask for help otherwise...

I was trying to update genghisapp to 2.3 and it kept loading 2.2.2. I tried to remove genghisapp from places because there seemed to be different versions on my system. Now I get this error, and gem uninstall/install doesn't solve it. What can I do about this? I'm quite new to Ruby / gems in general.

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:777:in `report_activate_error': Could not find RubyGem genghisapp (>= 0) (Gem::LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:211:in`activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:1056:in `gem'
    from /usr/bin/genghisapp:18

**Comment by 0x80** [comment]
I should probably add that I have installed ruby 2.0 on my system. So I don't quite understand why it keeps referring to 1.8

**Comment by 0x80** [comment]
After fighting with my system for a while I managed to get it fixed. Removed all gems, installed RVM,fixed permissions of /usr/local and reinstalled genghisapp and now it seems to use the right ruby version. Pfffew.

**Comment by bobthecow** [comment]
Heh. That'll do it.
